# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
script:
  - rm -rf AppDir
  - mkdir -p AppDir
  - cp -a RInstat AppDir/
  - mkdir -p AppDir/usr/share/icons/r-instat/96x96
  - cp r-instat.png AppDir/usr/share/icons/r-instat/96x96/
AppDir:
  path: AppDir
  app_info:
    id: org.r-instat
    name: R-Instat
    icon: r-instat
    version: latest
    exec: usr/bin/mono
    exec_args: --config $APPDIR/etc/mono/config $APPDIR/RInstat/instat.exe
  apt:
    arch:
      - amd64
    allow_unauthenticated: true
    sources:
      - sourceline: deb http://archive.ubuntu.com/ubuntu/ focal main restricted
          universe multiverse
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3B4FE6ACC0B21F32
      - sourceline: deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted
          universe multiverse
      - sourceline: deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted
          universe multiverse
      - sourceline: deb http://security.ubuntu.com/ubuntu/ focal-security main restricted
          universe multiverse
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3B4FE6ACC0B21F32
      - sourceline: deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x51716619E084DAB9
      - sourceline: deb http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal main
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF142A4D99F16EB04
    include:
      - bash
      - coreutils
      - dash
      - libgtk2.0-0
      - libx11-6
      - libxau6
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxdmcp6
      - mono-devel
      - mono-vbnc
      - r-base
      - r-cran-abind
      - r-cran-agricolae
      - r-cran-agridat
      - r-cran-algdesign
      - r-cran-arrangements
      - r-cran-ash
      - r-cran-askpass
      - r-cran-assertthat
      - r-cran-automap
      - r-cran-backports
      - r-cran-base64enc
      - r-cran-bayestestr
      - r-cran-bh
      - r-cran-biocmanager
      - r-cran-bitops
      - r-cran-brew
      - r-cran-brio
      - r-cran-broom
      - r-cran-bslib
      - r-cran-cachem
      - r-cran-callr
      - r-cran-candisc
      - r-cran-car
      - r-cran-cellranger
      - r-cran-changepoint
      - r-cran-checkmate
      - r-cran-chron
      - r-cran-circlize
      - r-cran-circstats
      - r-cran-circular
      - r-cran-classint
      - r-cran-cli
      - r-cran-clifro
      - r-cran-climdex.pcic
      - r-cran-clipr
      - r-cran-colorramps
      - r-cran-colorspace
      - r-cran-colourpicker
      - r-cran-combinat
      - r-cran-commonmark
      - r-cran-conquer
      - r-cran-corrplot
      - r-cran-countrycode
      - r-cran-cowplot
      - r-cran-cpp11
      - r-cran-crayon
      - r-cran-credentials
      - r-cran-crosstalk
      - r-cran-curl
      - r-cran-daag
      - r-cran-dae
      - r-cran-data.table
      - r-cran-date
      - r-cran-dbi
      - r-cran-dendextend
      - r-cran-deoptimr
      - r-cran-desc
      - r-cran-desctools
      - r-cran-devtools
      - r-cran-diffobj
      - r-cran-digest
      - r-cran-distillery
      - r-cran-dotcall64
      - r-cran-dplyr
      - r-cran-dt
      - r-cran-dummies
      - r-cran-e1071
      - r-cran-effectsize
      - r-cran-ellipse
      - r-cran-ellipsis
      - r-cran-emmeans
      - r-cran-envstats
      - r-cran-estimability
      - r-cran-evaluate
      - r-cran-evapotranspiration
      - r-cran-exact
      - r-cran-expm
      - r-cran-extradistr
      - r-cran-extrafont
      - r-cran-extrafontdb
      - r-cran-extremes
      - r-cran-factoextra
      - r-cran-factominer
      - r-cran-fansi
      - r-cran-faraway
      - r-cran-farver
      - r-cran-fastmap
      - r-cran-fields
      - r-cran-filelock
      - r-cran-fitdistrplus
      - r-cran-flashclust
      - r-cran-fnn
      - r-cran-forcats
      - r-cran-forecast
      - r-cran-formula
      - r-cran-fracdiff
      - r-cran-fs
      - r-cran-generics
      - r-cran-gensa
      - r-cran-geosphere
      - r-cran-gert
      - r-cran-getpass
      - r-cran-ggally
      - r-cran-ggdendro
      - r-cran-ggeffects
      - r-cran-ggfittext
      - r-cran-ggforce
      - r-cran-ggformula
      - r-cran-ggplot2
      - r-cran-ggplotify
      - r-cran-ggpubr
      - r-cran-ggrepel
      - r-cran-ggridges
      - r-cran-ggsci
      - r-cran-ggsignif
      - r-cran-ggstance
      - r-cran-ggtext
      - r-cran-ggthemes
      - r-cran-gh
      - r-cran-gitcreds
      - r-cran-gld
      - r-cran-globaloptions
      - r-cran-glue
      - r-cran-gmp
      - r-cran-goftest
      - r-cran-gridextra
      - r-cran-gridgraphics
      - r-cran-gridtext
      - r-cran-gstat
      - r-cran-gtable
      - r-cran-haven
      - r-cran-heplots
      - r-cran-hexbin
      - r-cran-highr
      - r-cran-hmisc
      - r-cran-hms
      - r-cran-htmltable
      - r-cran-htmltools
      - r-cran-htmlwidgets
      - r-cran-httpuv
      - r-cran-httr
      - r-cran-hunspell
      - r-cran-hydrogof
      - r-cran-hydrotsm
      - r-cran-imputets
      - r-cran-ini
      - r-cran-insight
      - r-cran-intervals
      - r-cran-isoband
      - r-cran-janeaustenr
      - r-cran-janitor
      - r-cran-jpeg
      - r-cran-jquerylib
      - r-cran-jsonlite
      - r-cran-kendall
      - r-cran-klar
      - r-cran-knitr
      - r-cran-labeling
      - r-cran-labelled
      - r-cran-later
      - r-cran-latticeextra
      - r-cran-lazyeval
      - r-cran-leaflet.providers
      - r-cran-leaps
      - r-cran-lifecycle
      - r-cran-lme4
      - r-cran-lmom
      - r-cran-lmomco
      - r-cran-lmoments
      - r-cran-lmtest
      - r-cran-lubridate
      - r-cran-magick
      - r-cran-magrittr
      - r-cran-mapdata
      - r-cran-mapproj
      - r-cran-maps
      - r-cran-maptools
      - r-cran-markdown
      - r-cran-matrixmodels
      - r-cran-matrixstats
      - r-cran-memoise
      - r-cran-mime
      - r-cran-miniui
      - r-cran-minqa
      - r-cran-modelr
      - r-cran-mosaiccore
      - r-cran-mosaicdata
      - r-cran-munsell
      - r-cran-mvtnorm
      - r-cran-ncdf4
      - r-cran-nloptr
      - r-cran-nortest
      - r-cran-numderiv
      - r-cran-nycflights13
      - r-cran-openair
      - r-cran-openxlsx
      - r-cran-parameters
      - r-cran-patchwork
      - r-cran-pbkrtest
      - r-cran-pbs
      - r-cran-pcict
      - r-cran-performance
      - r-cran-pillar
      - r-cran-pkgbuild
      - r-cran-pkgconfig
      - r-cran-pkgload
      - r-cran-plotly
      - r-cran-plotrix
      - r-cran-pls
      - r-cran-plyr
      - r-cran-png
      - r-cran-polyclip
      - r-cran-polynom
      - r-cran-praise
      - r-cran-prettyunits
      - r-cran-processx
      - r-cran-progress
      - r-cran-promises
      - r-cran-proxy
      - r-cran-ps
      - r-cran-purrr
      - r-cran-quadprog
      - r-cran-quantmod
      - r-cran-quantreg
      - r-cran-questionr
      - r-cran-r.methodss3
      - r-cran-r.oo
      - r-cran-r.utils
      - r-cran-r6
      - r-cran-rappdirs
      - r-cran-rcmdcheck
      - r-cran-rcolorbrewer
      - r-cran-rcpp
      - r-cran-rcpparmadillo
      - r-cran-rcppeigen
      - r-cran-rcpproll
      - r-cran-rcurl
      - r-cran-readods
      - r-cran-readr
      - r-cran-readxl
      - r-cran-rematch
      - r-cran-rematch2
      - r-cran-remotes
      - r-cran-reshape
      - r-cran-reshape2
      - r-cran-rje
      - r-cran-rlang
      - r-cran-rlist
      - r-cran-rmawgen
      - r-cran-rmysql
      - r-cran-robustbase
      - r-cran-rootsolve
      - r-cran-roxygen2
      - r-cran-rprojroot
      - r-cran-rrefine
      - r-cran-rstatix
      - r-cran-rstudioapi
      - r-cran-rtf
      - r-cran-rttf2pt1
      - r-cran-rvcheck
      - r-cran-rversions
      - r-cran-rvest
      - r-cran-rworldmap
      - r-cran-rworldxtra
      - r-cran-sandwich
      - r-cran-sass
      - r-cran-scales
      - r-cran-scatterplot3d
      - r-cran-selectr
      - r-cran-sessioninfo
      - r-cran-shades
      - r-cran-shape
      - r-cran-shiny
      - r-cran-shinyfiles
      - r-cran-shinyjs
      - r-cran-shinythemes
      - r-cran-sjlabelled
      - r-cran-sjmisc
      - r-cran-snakecase
      - r-cran-snowballc
      - r-cran-sodium
      - r-cran-sourcetools
      - r-cran-sp
      - r-cran-spacetime
      - r-cran-spam
      - r-cran-sparsem
      - r-cran-spei
      - r-cran-splus2r
      - r-cran-stinepack
      - r-cran-stringdist
      - r-cran-stringi
      - r-cran-stringr
      - r-cran-strucchange
      - r-cran-styler
      - r-cran-svglite
      - r-cran-sys
      - r-cran-systemfonts
      - r-cran-testthat
      - r-cran-tibble
      - r-cran-tidyr
      - r-cran-tidyselect
      - r-cran-tidytext
      - r-cran-timedate
      - r-cran-tokenizers
      - r-cran-trend
      - r-cran-tseries
      - r-cran-ttr
      - r-cran-tweenr
      - r-cran-units
      - r-cran-urca
      - r-cran-usethis
      - r-cran-utf8
      - r-cran-vars
      - r-cran-vctrs
      - r-cran-viridis
      - r-cran-viridislite
      - r-cran-visdat
      - r-cran-visreg
      - r-cran-waldo
      - r-cran-whisker
      - r-cran-withr
      - r-cran-xfun
      - r-cran-xml
      - r-cran-xml2
      - r-cran-xopen
      - r-cran-xtable
      - r-cran-xts
      - r-cran-yaml
      - r-cran-zip
      - r-cran-zoo
      - r-cran-zyp
  files:
    include: []
    exclude:
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*
      - usr/share/doc/*/NEWS.*
      - usr/share/doc/*/TODO.*
  after_bundle:
    - cp -f $APPDIR/usr/lib/R/etc/Renviron.orig $APPDIR/etc/R/Renviron
    - patch -u $APPDIR/etc/mono/config -i mono-config.patch
    - rm -rf temp-Rlibrary
    - mkdir -vp temp-Rlibrary
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$APPDIR/usr/lib/R/lib:$APPDIR/usr/lib/x86_64-linux-gnu R_LIBS_SITE=$(pwd)/temp-Rlibrary:$APPDIR/usr/lib/R/site-library:$APPDIR/usr/lib/R/library Rscript install_packages.R
    - cp -rf temp-Rlibrary/* $APPDIR/usr/lib/R/site-library/
  runtime:
    env:
      R_DOC_DIR: '$APPDIR/usr/share/R/doc' 
      R_HOME: '$APPDIR/usr/lib/R'
      R_INCLUDE_DIR: '$APPDIR/usr/share/R/include' 
      R_LIBS_SITE: '$APPDIR/usr/lib/R/site-library:$APPDIR/usr/lib/R/library'
      R_SHARE_DIR: '$APPDIR/usr/share/R/share' 
  test:
    ubuntu-xenial:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true
AppImage:
  arch: x86_64
  update-information: guess
