changelog:
  exclude:
    labels:
      - 'skip-releasenotes'
  categroies:
    - title: '⭐ Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐞 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
    - title: '🌦️ Climatic'
      labels: 
        - 'Climatic'
    - title: '📝 Procurement'
      labels: 
        - 'Procurement'
    - title: 'Other Changes'
      labels:
        - "*"
    

