'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class dlgDescribeOneVariableLikertGraph
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("instat.dlgDescribeOneVariableLikertGraph", GetType(dlgDescribeOneVariableLikertGraph).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=191}.
        '''</summary>
        Friend Shared ReadOnly Property cmdLikertOptions_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("cmdLikertOptions.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=117, Height=28}.
        '''</summary>
        Friend Shared ReadOnly Property cmdLikertOptions_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("cmdLikertOptions.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 5.
        '''</summary>
        Friend Shared ReadOnly Property cmdLikertOptions_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("cmdLikertOptions.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Likert Options.
        '''</summary>
        Friend Shared ReadOnly Property cmdLikertOptions_Text() As String
            Get
                Return ResourceManager.GetString("cmdLikertOptions.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to False.
        '''</summary>
        Friend Shared ReadOnly Property grpLikertOptions_Enabled() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grpLikertOptions.Enabled", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=223}.
        '''</summary>
        Friend Shared ReadOnly Property grpLikertOptions_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("grpLikertOptions.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=440, Height=119}.
        '''</summary>
        Friend Shared ReadOnly Property grpLikertOptions_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("grpLikertOptions.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property grpLikertOptions_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("grpLikertOptions.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Likert Graphs.
        '''</summary>
        Friend Shared ReadOnly Property grpLikertOptions_Text() As String
            Get
                Return ResourceManager.GetString("grpLikertOptions.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lblFactors_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lblFactors.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=280,Y=45}.
        '''</summary>
        Friend Shared ReadOnly Property lblFactors_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("lblFactors.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=45, Height=13}.
        '''</summary>
        Friend Shared ReadOnly Property lblFactors_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("lblFactors.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property lblFactors_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("lblFactors.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Factors:.
        '''</summary>
        Friend Shared ReadOnly Property lblFactors_Text() As String
            Get
                Return ResourceManager.GetString("lblFactors.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lblFactorsSummary_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lblFactorsSummary.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=280,Y=45}.
        '''</summary>
        Friend Shared ReadOnly Property lblFactorsSummary_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("lblFactorsSummary.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=45, Height=13}.
        '''</summary>
        Friend Shared ReadOnly Property lblFactorsSummary_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("lblFactorsSummary.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property lblFactorsSummary_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("lblFactorsSummary.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Factors:.
        '''</summary>
        Friend Shared ReadOnly Property lblFactorsSummary_Text() As String
            Get
                Return ResourceManager.GetString("lblFactorsSummary.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property rdoBar_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoBar.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=55,Y=22}.
        '''</summary>
        Friend Shared ReadOnly Property rdoBar_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoBar.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=41, Height=17}.
        '''</summary>
        Friend Shared ReadOnly Property rdoBar_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoBar.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 0.
        '''</summary>
        Friend Shared ReadOnly Property rdoBar_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoBar.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bar.
        '''</summary>
        Friend Shared ReadOnly Property rdoBar_Text() As String
            Get
                Return ResourceManager.GetString("rdoBar.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property rdoDensity_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoDensity.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=305,Y=22}.
        '''</summary>
        Friend Shared ReadOnly Property rdoDensity_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoDensity.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=60, Height=17}.
        '''</summary>
        Friend Shared ReadOnly Property rdoDensity_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoDensity.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property rdoDensity_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoDensity.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Density.
        '''</summary>
        Friend Shared ReadOnly Property rdoDensity_Text() As String
            Get
                Return ResourceManager.GetString("rdoDensity.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property rdoHeat_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoHeat.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=180,Y=22}.
        '''</summary>
        Friend Shared ReadOnly Property rdoHeat_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoHeat.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=48, Height=17}.
        '''</summary>
        Friend Shared ReadOnly Property rdoHeat_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoHeat.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property rdoHeat_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("rdoHeat.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heat.
        '''</summary>
        Friend Shared ReadOnly Property rdoHeat_Text() As String
            Get
                Return ResourceManager.GetString("rdoHeat.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=10,Y=10}.
        '''</summary>
        Friend Shared ReadOnly Property tbcLikert_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("tbcLikert.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=470, Height=394}.
        '''</summary>
        Friend Shared ReadOnly Property tbcLikert_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("tbcLikert.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 0.
        '''</summary>
        Friend Shared ReadOnly Property tbcLikert_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("tbcLikert.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=22}.
        '''</summary>
        Friend Shared ReadOnly Property tbpGraph_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("tbpGraph.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=3,Right=3,Bottom=3}.
        '''</summary>
        Friend Shared ReadOnly Property tbpGraph_Padding() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("tbpGraph.Padding", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=462, Height=368}.
        '''</summary>
        Friend Shared ReadOnly Property tbpGraph_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("tbpGraph.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 0.
        '''</summary>
        Friend Shared ReadOnly Property tbpGraph_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("tbpGraph.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Graph.
        '''</summary>
        Friend Shared ReadOnly Property tbpGraph_Text() As String
            Get
                Return ResourceManager.GetString("tbpGraph.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=22}.
        '''</summary>
        Friend Shared ReadOnly Property tbpSummary_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("tbpSummary.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=3,Right=3,Bottom=3}.
        '''</summary>
        Friend Shared ReadOnly Property tbpSummary_Padding() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("tbpSummary.Padding", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=462, Height=368}.
        '''</summary>
        Friend Shared ReadOnly Property tbpSummary_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("tbpSummary.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property tbpSummary_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("tbpSummary.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary.
        '''</summary>
        Friend Shared ReadOnly Property tbpSummary_Text() As String
            Get
                Return ResourceManager.GetString("tbpSummary.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ucrBase_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrBase.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AutoSizeMode similar to GrowAndShrink.
        '''</summary>
        Friend Shared ReadOnly Property ucrBase_AutoSizeMode() As System.Windows.Forms.AutoSizeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrBase.AutoSizeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.AutoSizeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=10,Y=407}.
        '''</summary>
        Friend Shared ReadOnly Property ucrBase_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrBase.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        '''</summary>
        Friend Shared ReadOnly Property ucrBase_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrBase.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=408, Height=52}.
        '''</summary>
        Friend Shared ReadOnly Property ucrBase_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrBase.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property ucrBase_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrBase.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkCentre_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkCentre.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=70}.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkCentre_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkCentre.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkCentre_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkCentre.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=120, Height=29}.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkCentre_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkCentre.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 5.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkCentre_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkCentre.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkIncludeHistogram_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkIncludeHistogram.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=45}.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkIncludeHistogram_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkIncludeHistogram.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkIncludeHistogram_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkIncludeHistogram.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=180, Height=29}.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkIncludeHistogram_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkIncludeHistogram.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 4.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkIncludeHistogram_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkIncludeHistogram.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkWrap_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkWrap.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=95}.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkWrap_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkWrap.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkWrap_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkWrap.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=120, Height=29}.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkWrap_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkWrap.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 7.
        '''</summary>
        Friend Shared ReadOnly Property ucrChkWrap_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrChkWrap.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ucrNudCentre_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrNudCentre.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=140,Y=70}.
        '''</summary>
        Friend Shared ReadOnly Property ucrNudCentre_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrNudCentre.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        '''</summary>
        Friend Shared ReadOnly Property ucrNudCentre_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrNudCentre.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=50, Height=20}.
        '''</summary>
        Friend Shared ReadOnly Property ucrNudCentre_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrNudCentre.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 6.
        '''</summary>
        Friend Shared ReadOnly Property ucrNudCentre_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrNudCentre.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ucrNudWrap_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrNudWrap.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=140,Y=95}.
        '''</summary>
        Friend Shared ReadOnly Property ucrNudWrap_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrNudWrap.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        '''</summary>
        Friend Shared ReadOnly Property ucrNudWrap_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrNudWrap.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=50, Height=20}.
        '''</summary>
        Friend Shared ReadOnly Property ucrNudWrap_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrNudWrap.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 8.
        '''</summary>
        Friend Shared ReadOnly Property ucrNudWrap_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrNudWrap.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AutoSizeMode similar to GrowAndShrink.
        '''</summary>
        Friend Shared ReadOnly Property ucrPnlGraphType_AutoSizeMode() As System.Windows.Forms.AutoSizeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrPnlGraphType.AutoSizeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.AutoSizeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=15}.
        '''</summary>
        Friend Shared ReadOnly Property ucrPnlGraphType_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrPnlGraphType.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        '''</summary>
        Friend Shared ReadOnly Property ucrPnlGraphType_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrPnlGraphType.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=428, Height=28}.
        '''</summary>
        Friend Shared ReadOnly Property ucrPnlGraphType_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrPnlGraphType.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property ucrPnlGraphType_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrPnlGraphType.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ucrReceiverMultipleLikert_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrReceiverMultipleLikert.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=280,Y=60}.
        '''</summary>
        Friend Shared ReadOnly Property ucrReceiverMultipleLikert_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrReceiverMultipleLikert.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        '''</summary>
        Friend Shared ReadOnly Property ucrReceiverMultipleLikert_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrReceiverMultipleLikert.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=120, Height=130}.
        '''</summary>
        Friend Shared ReadOnly Property ucrReceiverMultipleLikert_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrReceiverMultipleLikert.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property ucrReceiverMultipleLikert_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrReceiverMultipleLikert.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ucrReceiverMultipleLikertSummary_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrReceiverMultipleLikertSummary.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=280,Y=60}.
        '''</summary>
        Friend Shared ReadOnly Property ucrReceiverMultipleLikertSummary_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrReceiverMultipleLikertSummary.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        '''</summary>
        Friend Shared ReadOnly Property ucrReceiverMultipleLikertSummary_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrReceiverMultipleLikertSummary.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=120, Height=130}.
        '''</summary>
        Friend Shared ReadOnly Property ucrReceiverMultipleLikertSummary_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrReceiverMultipleLikertSummary.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property ucrReceiverMultipleLikertSummary_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrReceiverMultipleLikertSummary.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AutoSizeMode similar to GrowAndShrink.
        '''</summary>
        Friend Shared ReadOnly Property ucrSaveGraph_AutoSizeMode() As System.Windows.Forms.AutoSizeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSaveGraph.AutoSizeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.AutoSizeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=344}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSaveGraph_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSaveGraph.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=5,Right=4,Bottom=5}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSaveGraph_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSaveGraph.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=400, Height=24}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSaveGraph_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSaveGraph.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 4.
        '''</summary>
        Friend Shared ReadOnly Property ucrSaveGraph_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSaveGraph.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AutoSizeMode similar to GrowAndShrink.
        '''</summary>
        Friend Shared ReadOnly Property ucrSaveSummary_AutoSizeMode() As System.Windows.Forms.AutoSizeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSaveSummary.AutoSizeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.AutoSizeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=10,Y=336}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSaveSummary_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSaveSummary.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=5,Right=4,Bottom=5}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSaveSummary_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSaveSummary.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=400, Height=24}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSaveSummary_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSaveSummary.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property ucrSaveSummary_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSaveSummary.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ucrSelectorLikert_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSelectorLikert.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=10,Y=10}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSelectorLikert_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSelectorLikert.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSelectorLikert_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSelectorLikert.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=267, Height=229}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSelectorLikert_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSelectorLikert.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 0.
        '''</summary>
        Friend Shared ReadOnly Property ucrSelectorLikert_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSelectorLikert.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ucrSelectorLikertSummary_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSelectorLikertSummary.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=10,Y=10}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSelectorLikertSummary_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSelectorLikertSummary.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSelectorLikertSummary_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSelectorLikertSummary.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=264, Height=227}.
        '''</summary>
        Friend Shared ReadOnly Property ucrSelectorLikertSummary_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSelectorLikertSummary.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 0.
        '''</summary>
        Friend Shared ReadOnly Property ucrSelectorLikertSummary_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrSelectorLikertSummary.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
    End Class
End Namespace
