' Instat-R
' Copyright (C) 2015
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License k
' along with this program.  If not, see <http://www.gnu.org/licenses/>.

Imports instat.Translations
Public Class dlgJitter
    Public bReset As Boolean = True
    Public bFirstLoad As Boolean = True
    Private clsOperatorParameter As New ROperator
    Private clsDefaultFunction As New RFunction

    Private Sub dlgJitter_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        If bFirstLoad Then
            InitialiseDialog()
            bFirstLoad = False
        End If
        If bReset Then
            SetDefaults()
        End If
        SetRCodeforControls(bReset)
        bReset = False
        autoTranslate(Me)
    End Sub


    'MAX
    '# dlgJitter code generated by the dialog Jitter
    'value <- InstatDataObject$get_columns_from_data(col_name="value", data_name="data1_stackedNoCarry")
    'Jitter_values1 <- value + runif(max=NUMBER, min=-NUMBER, n=10)
    'InstatDataObject$add_columns_to_data(col_data = Jitter_values1, col_name = "Jitter_values1", data_name = "data1_stackedNoCarry")

    'MIN AND MAX
    '# dlgJitter code generated by the dialog Jitter
    'Jitter_values2 <- value + runif(n=10, min=0, max=1)
    'InstatDataObject$add_columns_to_data(col_data = Jitter_values2, col_name = "Jitter_values2", data_name = "data1_stackedNoCarry")

    Private Sub InitialiseDialog()
        ucrBase.iHelpTopicID = 396

        'ucrReceiver
        ucrReceiverJitter.Selector = ucrSelectorForJitter
        ucrReceiverJitter.SetMeAsReceiver()
        ucrReceiverJitter.SetIncludedDataTypes({"numeric"})
        ucrReceiverJitter.SetParameterIsRFunction()

        'operator parameter
        clsOperatorParameter.SetOperation("+")

        'rdo Buttons
        ' have two radio buttons - each with two parameters which are the same name but different selector
        ' radio buttons

        ucrPnlDistance.AddRadioButton(rdoMaximumDistanceFromZero)
        ucrPnlDistance.AddRadioButton(rdoMinimumAndMaximum)

        ucrPnlDistance.AddParameterPresentCondition(rdoMaximumDistanceFromZero, "max")
        ucrPnlDistance.AddParameterPresentCondition(rdoMaximumDistanceFromZero, "min")
        ucrPnlDistance.AddParameterPresentCondition(rdoMinimumAndMaximum, "max")
        ucrPnlDistance.AddParameterPresentCondition(rdoMinimumAndMaximum, "min")

        ' link
        ucrPnlDistance.AddToLinkedControls(ucrInputMaximumDistanceFromZero, {rdoMaximumDistanceFromZero}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True)
        ucrPnlDistance.AddToLinkedControls(ucrInputMinimum, {rdoMinimumAndMaximum}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True)
        ucrPnlDistance.AddToLinkedControls(ucrInputMaximum, {rdoMinimumAndMaximum}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True)

        'ucrInputs
        '        ucrInputMaximumDistanceFromZero.SetParameter(New RParameter("max", ))
        ucrInputMaximumDistanceFromZero.SetValidationTypeAsNumeric()
        ucrInputMaximumDistanceFromZero.AddQuotesIfUnrecognised = False
        ucrInputMaximumDistanceFromZero.SetRDefault(1)
        ' this has two parameters associated with it, however - Max and Min!

        ucrInputMinimum.SetParameter(New RParameter("min"))
        ucrInputMinimum.bAddRemoveParameter = False
        ucrInputMinimum.SetValidationTypeAsNumeric()
        ucrInputMinimum.SetRDefault(0)
        ucrInputMinimum.AddQuotesIfUnrecognised = False

        ucrInputMaximum.SetParameter(New RParameter("max"))
        ucrInputMaximum.bAddRemoveParameter = False
        ucrInputMaximum.SetValidationTypeAsNumeric()
        ucrInputMaximum.SetRDefault(1)
        ucrInputMaximum.AddQuotesIfUnrecognised = False

        'ucrInputNewColName
        ucrInputNewColName.SetIsComboBox()
        ucrInputNewColName.SetSaveTypeAsColumn()
        ucrInputNewColName.SetDataFrameSelector(ucrSelectorForJitter.ucrAvailableDataFrames)
        ucrInputNewColName.SetLabelText("Column Name:")
        ucrInputNewColName.SetPrefix("Jitter_values")

        clsDefaultFunction.AddParameter("n", ucrSelectorForJitter.ucrAvailableDataFrames.iDataFrameLength)
        clsOperatorParameter.AddParameter(0, clsRFunctionParameter:=clsDefaultFunction)
    End Sub

    Private Sub SetDefaults()
        ucrSelectorForJitter.Reset()
        rdoMinimumAndMaximum.Checked = True

        clsDefaultFunction.SetRCommand("runif")
        clsDefaultFunction.AddParameter("min", "0")
        clsDefaultFunction.AddParameter("max", "1")
        clsDefaultFunction.SetAssignTo(strTemp:=ucrInputNewColName.GetText, strTempDataframe:=ucrSelectorForJitter.ucrAvailableDataFrames.cboAvailableDataFrames.Text, strTempColumn:=ucrInputNewColName.GetText)
        ucrBase.clsRsyntax.SetBaseRFunction(clsDefaultFunction)

        clsOperatorParameter.AddParameter(0, clsRFunctionParameter:=clsDefaultFunction)
    End Sub

    Private Sub SetRCodeforControls(bReset As Boolean)
        ucrPnlDistance.SetRCode(clsDefaultFunction, bReset)
        ucrInputMaximum.SetRCode(clsDefaultFunction, bReset)
        ucrInputMinimum.SetRCode(clsDefaultFunction, bReset)
        ucrInputMaximumDistanceFromZero.SetRCode(clsDefaultFunction, bReset)
        ucrSelectorForJitter.SetRCode(clsDefaultFunction, bReset)
        ucrInputNewColName.SetRCode(clsDefaultFunction, bReset)
        '        ucrReceiverJitter.SetRCode(clsOperatorParameter, bReset)
    End Sub

    Private Sub ucrBase_ClickReset(sender As Object, e As EventArgs) Handles ucrBase.ClickReset
        SetDefaults()
        SetRCodeforControls(True)
        TestOKEnabled()
    End Sub

    Private Sub TestOKEnabled()
        If Not ucrReceiverJitter.IsEmpty AndAlso ucrInputNewColName.IsComplete AndAlso ((rdoMaximumDistanceFromZero.Checked AndAlso Not ucrInputMaximumDistanceFromZero.IsEmpty) OrElse Not rdoMaximumDistanceFromZero.Checked) AndAlso ((rdoMinimumAndMaximum.Checked AndAlso Not ucrInputMaximum.IsEmpty AndAlso Not ucrInputMinimum.IsEmpty) OrElse Not rdoMinimumAndMaximum.Checked) Then
            ucrBase.OKEnabled(True)
        Else
            ucrBase.OKEnabled(False)
        End If
    End Sub

    Private Sub Distance()
        If rdoMaximumDistanceFromZero.Checked Then
            If Not ucrInputMaximumDistanceFromZero.IsEmpty Then
                clsDefaultFunction.AddParameter("min", -(ucrInputMaximumDistanceFromZero.GetText))
                clsDefaultFunction.AddParameter("max", ucrInputMaximumDistanceFromZero.GetText)
            Else
                clsDefaultFunction.RemoveParameterByName("min")
                clsDefaultFunction.RemoveParameterByName("max")
            End If
        Else
            If Not ucrInputMinimum.IsEmpty Then
                clsDefaultFunction.AddParameter("min", ucrInputMinimum.GetText)
            Else
                clsDefaultFunction.RemoveParameterByName("min")
            End If
            If Not ucrInputMaximum.IsEmpty Then
                clsDefaultFunction.AddParameter("max", ucrInputMaximum.GetText) '
            Else
                clsDefaultFunction.RemoveParameterByName("max")
            End If
        End If
    End Sub

    Private Sub ucrSelectorForJitter_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrSelectorForJitter.ControlValueChanged
        clsDefaultFunction.AddParameter("n", ucrSelectorForJitter.ucrAvailableDataFrames.iDataFrameLength)
    End Sub

    Private Sub ucrForDistance_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrInputMaximum.ControlValueChanged, ucrInputMaximumDistanceFromZero.ControlValueChanged, ucrInputMinimum.ControlValueChanged, ucrPnlDistance.ControlValueChanged
        Distance()
    End Sub

    Private Sub ucrReceiverJitter_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrReceiverJitter.ControlValueChanged
        clsOperatorParameter.AddParameter(1, clsRFunctionParameter:=ucrReceiverJitter.GetVariables)
    End Sub

    Private Sub ucrForTestOK_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrReceiverJitter.ControlContentsChanged, ucrInputNewColName.ControlContentsChanged, ucrPnlDistance.ControlContentsChanged, ucrInputMaximumDistanceFromZero.ControlContentsChanged, ucrInputMaximum.ControlContentsChanged, ucrInputMinimum.ControlContentsChanged
        TestOKEnabled()
    End Sub

    Private Sub ucrPnlDistance_ControlValueChanged(ucrChangedControl As ucrCore)

    End Sub
End Class