' Instat-R
' Copyright (C) 2015
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License k
' along with this program.  If not, see <http://www.gnu.org/licenses/>.

Imports System.Globalization
Imports System.Threading
Imports instat.Translations

Public Class dlgOptions
    Public strComment As String = "code generated by the dialog"
    Public strCurrLanguage As String
    'Define the Fonts dialog (only one)
    Dim dlgFont As New FontDialog

    Private Sub dlgOptions_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        autoTranslate(Me)
        txtComment.Text = strComment
        strCurrLanguage = Thread.CurrentThread.CurrentCulture.ThreeLetterISOLanguageName
        rdoEnglish.Checked = False
        rdoFrench.Checked = False
        rdoKiswahili.Checked = False

        Select Case strCurrLanguage
            Case "eng"
                rdoEnglish.Checked = True
            Case "fra"
                rdoFrench.Checked = True
            Case "swa"
                rdoKiswahili.Checked = True
        End Select
        cmdApply.Enabled = False
        'cmdOk.Enabled = False
        'Loads the current font and color
        txtScriptFont.Text = frmMain.clsRLink.fScript.FontFamily.Name
        txtScriptColor.Text = frmMain.clsRLink.clrScript.Name
        txtScriptColor.ForeColor = frmMain.clsRLink.clrScript
        txtScriptSize.Text = frmMain.clsRLink.fScript.Size
        'For the output
        txtOutputFont.Text = frmMain.clsRLink.fScript.FontFamily.Name
        txtOutputcolor.Text = frmMain.clsRLink.clrScript.Name
        txtOutputcolor.ForeColor = frmMain.clsRLink.clrScript
        txtOutputSize.Text = frmMain.clsRLink.fScript.Size
    End Sub
    Private Sub cmdCancel_Click(sender As Object, e As EventArgs) Handles cmdCancel.Click
        Me.Close()
    End Sub

    Private Sub cmdOk_Click(sender As Object, e As EventArgs) Handles cmdOk.Click
        cmdApply_Click(sender, e)
        frmMain.clsRLink.setFormatOutput(txtOutputFont.Font, txtOutputcolor.ForeColor)
        frmMain.clsRLink.setFormatScript(txtScriptFont.Font, txtScriptColor.ForeColor)
        Me.Close()
    End Sub

    Private Sub cmdApply_Click(sender As Object, e As EventArgs) Handles cmdApply.Click
        strComment = txtComment.Text
        If rdoEnglish.Checked Then
            Thread.CurrentThread.CurrentCulture = New CultureInfo("en-US")
            Thread.CurrentThread.CurrentUICulture = New CultureInfo("en-US")
            strCurrLanguage = "eng"
        End If

        If rdoFrench.Checked Then
            Thread.CurrentThread.CurrentCulture = New CultureInfo("fr-FR")
            Thread.CurrentThread.CurrentUICulture = New CultureInfo("fr-FR")
            strCurrLanguage = "fra"
        End If

        If rdoKiswahili.Checked Then
            Thread.CurrentThread.CurrentCulture = New CultureInfo("sw-KE")
            Thread.CurrentThread.CurrentUICulture = New CultureInfo("sw-KE")
            strCurrLanguage = "swa"
        End If
        cmdApply.Enabled = False
        cmdOk.Enabled = False
        autoTranslate(Me)

        If frmMain.Visible Then
            autoTranslate(frmMain)
        End If

        If frmCommand.Visible Then
            autoTranslate(frmCommand)
        End If

        If frmEditor.Visible Then
            autoTranslate(frmEditor)
        End If

        If frmLog.Visible Then
            autoTranslate(frmLog)
        End If

        If frmMetaData.Visible Then
            autoTranslate(frmMetaData)
        End If

        If frmScript.Visible Then
            autoTranslate(frmScript)
        End If

        If frmVariables.Visible Then
            autoTranslate(frmVariables)
        End If
    End Sub

    Private Sub rdoKiswahili_CheckedChanged(sender As Object, e As EventArgs) Handles rdoKiswahili.CheckedChanged
        cmdApply.Enabled = True
        cmdOk.Enabled = True
    End Sub

    Private Sub rdoFrench_CheckedChanged(sender As Object, e As EventArgs) Handles rdoFrench.CheckedChanged
        cmdApply.Enabled = True
        cmdOk.Enabled = True
    End Sub

    Private Sub rdoEnglish_CheckedChanged(sender As Object, e As EventArgs) Handles rdoEnglish.CheckedChanged
        cmdApply.Enabled = True
        cmdOk.Enabled = True
    End Sub

    Private Sub txtComment_TextChanged(sender As Object, e As EventArgs) Handles txtComment.TextChanged
        cmdApply.Enabled = True
        cmdOk.Enabled = True
    End Sub

    Private Sub cmdScriptChange_Click(sender As Object, e As EventArgs) Handles cmdScriptChange.Click
        dlgFont.ShowColor = True
        dlgFont.MaxSize = 15
        dlgFont.MinSize = 8
        If dlgFont.ShowDialog = DialogResult.OK Then
            txtScriptFont.Text = dlgFont.Font.FontFamily.Name
            txtScriptColor.ForeColor = dlgFont.Color
            txtScriptFont.Font = dlgFont.Font
            txtScriptColor.Text = dlgFont.Color.Name
            txtScriptSize.Text = dlgFont.Font.Size
            dlgFont.Reset()
        End If
    End Sub

    Private Sub cmdOutputChange_Click(sender As Object, e As EventArgs) Handles cmdOutputChange.Click
        dlgFont.ShowColor = True
        dlgFont.MaxSize = 15
        dlgFont.MinSize = 8
        If dlgFont.ShowDialog = DialogResult.OK Then
            txtOutputFont.Text = dlgFont.Font.FontFamily.Name
            txtOutputFont.Font = dlgFont.Font
            txtOutputcolor.Text = dlgFont.Color.Name
            txtOutputcolor.ForeColor = dlgFont.Color
            txtOutputSize.Text = dlgFont.Font.Size
            dlgFont.Reset()
        End If
    End Sub

    Private Sub cmdCommentsChange_Click(sender As Object, e As EventArgs) Handles cmdCommentsChange.Click
        dlgFont.ShowColor = True
        dlgFont.MaxSize = 15
        dlgFont.MinSize = 8
        If dlgFont.ShowDialog = DialogResult.OK Then
            txtCommentsFont.Text = dlgFont.Font.FontFamily.Name
            txtCommentsColor.Text = dlgFont.Color.Name
            txtCommentsSize.Text = dlgFont.Font.Size
        End If
    End Sub
End Class