' R- Instat
' Copyright (C) 2015-2017
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License 
' along with this program.  If not, see <http://www.gnu.org/licenses/>.

Imports instat.Translations

Public Class sdgSummaryThemes
    Private clsThemesTabOptionsFunction As New RFunction
    Private bRCodeSet As Boolean = False
    Private bControlsInitialised As Boolean = False

    Private Sub sdgSummaryThemes_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        autoTranslate(Me)
    End Sub

    Private Sub InitialiseControls()
        Dim dctAlignment, dctWeights, dctStyles, dctBorderStyles, dctTextTransform, dctLayouts As New Dictionary(Of String, String)

        dctWeights.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctWeights.Add("Normal", Chr(34) & "normal" & Chr(34))
        dctWeights.Add("Bold", Chr(34) & "bold" & Chr(34))
        dctWeights.Add("Lighter", Chr(34) & "lighter" & Chr(34))
        dctWeights.Add("Bolder", Chr(34) & "bolder" & Chr(34))

        dctAlignment.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctAlignment.Add("Left", Chr(34) & "left" & Chr(34))
        dctAlignment.Add("Right", Chr(34) & "right" & Chr(34))
        dctAlignment.Add("Center", Chr(34) & "center" & Chr(34))

        dctStyles.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctStyles.Add("Normal", Chr(34) & "normal" & Chr(34))
        dctStyles.Add("Italic", Chr(34) & "italic" & Chr(34))
        dctStyles.Add("Oblique", Chr(34) & "oblique" & Chr(34))

        dctBorderStyles.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctBorderStyles.Add("Solid", Chr(34) & "solid" & Chr(34))
        dctBorderStyles.Add("Dashed", Chr(34) & "dashed" & Chr(34))
        dctBorderStyles.Add("Dotted", Chr(34) & "dotted" & Chr(34))

        dctTextTransform.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctTextTransform.Add("Uppercase", Chr(34) & "uppercase" & Chr(34))
        dctTextTransform.Add("Lowercase", Chr(34) & "lowercase" & Chr(34))
        dctTextTransform.Add("Capitalize", Chr(34) & "capitalize" & Chr(34))

        dctLayouts.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctLayouts.Add("Auto", Chr(34) & "auto" & Chr(34))
        dctLayouts.Add("Fixed", Chr(34) & "fixed" & Chr(34))

        ucrChkBackgroundColour.SetText("Background Colour")
        ucrInputBackgroundColour.SetParameter(New RParameter("heading.background.color"))
        ucrChkBackgroundColour.AddParameterPresentCondition(True, "heading.background.color")
        ucrChkBackgroundColour.AddParameterPresentCondition(False, "heading.background.color", False)

        ucrChkAlignment.SetText("Alignment")
        ucrInputAlignment.SetParameter(New RParameter("heading.align"))
        ucrInputAlignment.SetItems(dctAlignment)
        ucrChkAlignment.AddParameterPresentCondition(True, "heading.align")
        ucrChkAlignment.AddParameterPresentCondition(False, "heading.align", False)

        ucrChkFontSize.SetText("Font Size")
        ucrNudFontSize.SetParameter(New RParameter("heading.title.font.size"))
        ucrNudFontSize.SetRDefault(0)
        ucrChkFontSize.AddParameterPresentCondition(True, "heading.title.font.size")
        ucrChkFontSize.AddParameterPresentCondition(False, "heading.title.font.size", False)

        ucrChkSubTitleSize.SetText("Font Size")
        ucrNudSubTitleSize.SetParameter(New RParameter("heading.subtitle.font.size"))
        ucrNudSubTitleSize.SetRDefault(0)
        ucrChkSubTitleSize.AddParameterPresentCondition(True, "heading.subtitle.font.size")
        ucrChkSubTitleSize.AddParameterPresentCondition(False, "heading.subtitle.font.size", False)

        ucrChkFontWeight.SetText("Font Weights")
        ucrInputFontWeight.SetParameter(New RParameter("heading.title.font.weight"))
        ucrInputFontWeight.SetItems(dctWeights)
        ucrChkFontWeight.AddParameterPresentCondition(True, "heading.title.font.weight")
        ucrChkFontWeight.AddParameterPresentCondition(False, "heading.title.font.weight", False)

        ucrChkSubTitleWeight.SetText("Font Weights")
        ucrInputSubTitleWeight.SetParameter(New RParameter("heading.subtitle.font.weight"))
        ucrInputSubTitleWeight.SetItems(dctWeights)
        ucrChkSubTitleWeight.AddParameterPresentCondition(True, "heading.subtitle.font.weight")
        ucrChkSubTitleWeight.AddParameterPresentCondition(False, "heading.subtitle.font.weight", False)

        ucrChkBoxWidth.SetText("Width of box")
        ucrNudBoxWidth.SetParameter(New RParameter("heading.padding"))
        ucrNudBoxWidth.SetRDefault(0)
        ucrChkBoxWidth.AddParameterPresentCondition(True, "heading.padding")
        ucrChkBoxWidth.AddParameterPresentCondition(False, "heading.padding", False)

        ucrChkBoxWidth.SetText("Length of box")
        ucrNudBoxWidth.SetParameter(New RParameter("heading.padding.horizontal"))
        ucrNudBoxWidth.SetRDefault(0)
        ucrChkBoxWidth.AddParameterPresentCondition(True, "heading.padding.horizontal")
        ucrChkBoxWidth.AddParameterPresentCondition(False, "heading.padding,horizontal", False)

        ucrChkBottomWidth.SetText("Width of bottom border")
        ucrNudBottomWidth.SetParameter(New RParameter("heading.border.bottom.width"))
        ucrNudBottomWidth.SetRDefault(0)
        ucrChkBottomWidth.AddParameterPresentCondition(True, "heading.border.bottom.width")
        ucrChkBottomWidth.AddParameterPresentCondition(False, "heading.border.bottom.width", False)

        ucrChkBottomStyle.SetText("Style of bottom border")
        ucrInputBottomStyle.SetParameter(New RParameter("heading.border.bottom.style"))
        ucrInputBottomStyle.SetItems(dctBorderStyles)
        ucrChkBottomStyle.AddParameterPresentCondition(True, "heading.border.bottom.style")
        ucrChkBottomStyle.AddParameterPresentCondition(False, "heading.border.bottom.style", False)

        ucrChkBottomColour.SetText("Colour of bottom border")
        ucrInputBottomColour.SetParameter(New RParameter("heading.border.bottom.color"))
        ucrChkBottomColour.AddParameterPresentCondition(True, "heading.border.bottom.color")
        ucrChkBottomColour.AddParameterPresentCondition(False, "heading.border.bottom.color", False)

        ucrChkSideWidth.SetText("Width of side border")
        ucrNudSideWidth.SetParameter(New RParameter("heading.border.lr.width"))
        ucrNudSideWidth.SetRDefault(0)
        ucrChkSideWidth.AddParameterPresentCondition(True, "heading.border.lr.width")
        ucrChkSideWidth.AddParameterPresentCondition(False, "heading.border.lr.width", False)

        ucrChkSideStyle.SetText("Style of side border")
        ucrInputSideStyle.SetParameter(New RParameter("heading.border.lr.style"))
        ucrInputSideStyle.SetItems(dctBorderStyles)
        ucrChkSideStyle.AddParameterPresentCondition(True, "heading.border.lr.style")
        ucrChkSideStyle.AddParameterPresentCondition(False, "heading.border.lr.style", False)

        ucrChkSideColour.SetText("Colour of side border")
        ucrInputSideColour.SetParameter(New RParameter("heading.border.lr.colour"))
        ucrChkSideColour.AddParameterPresentCondition(True, "heading.border.lr.colour")
        ucrChkSideColour.AddParameterPresentCondition(False, "heading.border.lr.colour", False)

        ucrChkBackgroundColour.AddToLinkedControls(ucrInputBackgroundColour, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkAlignment.AddToLinkedControls(ucrInputAlignment, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkFontSize.AddToLinkedControls(ucrNudFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkFontWeight.AddToLinkedControls(ucrInputFontWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="null")
        ucrChkSubTitleSize.AddToLinkedControls(ucrNudSubTitleSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkSubTitleWeight.AddToLinkedControls(ucrInputSubTitleWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkBoxWidth.AddToLinkedControls(ucrNudBoxWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkBoxLength.AddToLinkedControls(ucrNudBoxLength, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkBottomWidth.AddToLinkedControls(ucrNudBottomWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkBottomStyle.AddToLinkedControls(ucrInputBottomStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkBottomColour.AddToLinkedControls(ucrInputBottomColour, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkSideWidth.AddToLinkedControls(ucrNudSideWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkSideStyle.AddToLinkedControls(ucrInputSideStyle, {True}, bNewLinkedHideIfParameterMissing:=True, bNewLinkedAddRemoveParameter:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkSideColour.AddToLinkedControls(ucrInputSideColour, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")

        ucrChkTableWidth.SetText("Width")
        ucrInputTableFontWeight.SetParameter(New RParameter("table.width"))
        ucrChkTableWidth.AddParameterPresentCondition(True, "table.width")
        ucrChkTableWidth.AddParameterPresentCondition(False, "table.width", False)

        ucrChkTableLayout.SetText("Layout")
        ucrInputTableLayout.SetParameter(New RParameter("table.layout"))
        ucrInputTableLayout.SetItems(dctLayouts)
        ucrChkTableLayout.AddParameterPresentCondition(True, "table.layout")
        ucrChkTableLayout.AddParameterPresentCondition(False, "table.layout", False)

        ucrChkTableAlign.SetText("Alignment")
        ucrInputTableAlign.SetParameter(New RParameter("table.align"))
        ucrInputTableAlign.SetItems(dctAlignment)
        ucrChkTableAlign.AddParameterPresentCondition(True, "table.align")
        ucrChkTableAlign.AddParameterPresentCondition(False, "table.align", False)

        ucrChkTableBackColor.SetText("Background color")
        ucrTableBackgroundColors.SetParameter(New RParameter("table.background.color"))
        ucrChkTableBackColor.AddParameterPresentCondition(True, "table.background.color")
        ucrChkTableBackColor.AddParameterPresentCondition(False, "table.background.color", False)

        ucrChkTableFontNames.SetText("Font names")
        ucrInputTableFontNames.SetParameter(New RParameter("table.font.names"))
        ucrChkTableFontNames.AddParameterPresentCondition(True, "table.font.names")
        ucrChkTableFontNames.AddParameterPresentCondition(False, "table.font.names", False)

        ucrChkTableFontSize.SetText("Font size")
        ucrNudTableFontSize.SetParameter(New RParameter("table.font.size"))
        ucrNudTableFontSize.SetRDefault(0)
        ucrChkTableFontSize.AddParameterPresentCondition(True, "table.font.size")
        ucrChkTableFontSize.AddParameterPresentCondition(False, "table.font.size", False)

        ucrChkTableFontWeight.SetText("Font weight")
        ucrInputTableFontWeight.SetParameter(New RParameter("table.font.weight"))
        ucrInputTableFontWeight.SetItems(dctWeights)
        ucrChkTableFontWeight.AddParameterPresentCondition(True, "table.font.weight")
        ucrChkTableFontWeight.AddParameterPresentCondition(False, "table.font.weight", False)

        ucrChkTableFontStyle.SetText("Font style")
        ucrInputTableFontStyle.SetParameter(New RParameter("table.font.style"))
        ucrInputTableFontStyle.SetItems(dctStyles)
        ucrChkTableFontStyle.AddParameterPresentCondition(True, "table.font.style")
        ucrChkTableFontStyle.AddParameterPresentCondition(False, "table.font.style", False)

        ucrChkTableFontColor.SetText("Font color")
        ucrInputTableFontColor.SetParameter(New RParameter("table.font.color"))
        ucrChkTableFontColor.AddParameterPresentCondition(True, "table.font.color")
        ucrChkTableFontColor.AddParameterPresentCondition(False, "table.font.color", False)

        ucrChkTableTopStyle.SetText("Top border style")
        ucrInputTableTopStyle.SetParameter(New RParameter("table.border.top.style"))
        ucrInputTableTopStyle.SetItems(dctBorderStyles)
        ucrChkTableTopStyle.AddParameterPresentCondition(True, "table.border.top.style")
        ucrChkTableTopStyle.AddParameterPresentCondition(False, "table.border.top.style", False)

        ucrChkTableTopWidth.SetText("Top border Width")
        ucrNudTableTopWidth.SetParameter(New RParameter("table.border.top.width"))
        ucrNudTableTopWidth.SetRDefault(0)
        ucrChkTableTopWidth.AddParameterPresentCondition(True, "table.border.top.width")
        ucrChkTableTopWidth.AddParameterPresentCondition(False, "table.border.top.width", False)

        ucrChkTableTopColor.SetText("Top border color")
        ucrInputTableTopColor.SetParameter(New RParameter("table.border.top.color"))
        ucrChkTableTopColor.AddParameterPresentCondition(True, "table.border.top.color")
        ucrChkTableTopColor.AddParameterPresentCondition(False, "table.border.top.color", False)

        ucrChkTableRightStyle.SetText("Right border style")
        ucrInputTableRightStyle.SetParameter(New RParameter("table.border.right.style"))
        ucrInputTableRightStyle.SetItems(dctBorderStyles)
        ucrChkTableRightStyle.AddParameterPresentCondition(True, "table.border.right.style")
        ucrChkTableRightStyle.AddParameterPresentCondition(False, "table.border.right.style", False)

        ucrChkTableRightWidth.SetText("Right border Width")
        ucrNudTableRightWidth.SetParameter(New RParameter("table.border.right.width"))
        ucrNudTableRightWidth.SetRDefault(0)
        ucrChkTableRightWidth.AddParameterPresentCondition(True, "table.border.right.width")
        ucrChkTableRightWidth.AddParameterPresentCondition(False, "table.border.right.width", False)

        ucrChkTableRightColor.SetText("Right border color")
        ucrInputTableRightColor.SetParameter(New RParameter("table.border.right.color"))
        ucrChkTableRightColor.AddParameterPresentCondition(True, "table.border.right.color")
        ucrChkTableRightColor.AddParameterPresentCondition(False, "table.border.right.color", False)

        ucrChkTableBottomStyle.SetText("Bottom border style")
        ucrInputTableBottomStyle.SetParameter(New RParameter("table.border.bottom.style"))
        ucrInputTableBottomStyle.SetItems(dctBorderStyles)
        ucrChkTableBottomStyle.AddParameterPresentCondition(True, "table.border.bottom.style")
        ucrChkTableBottomStyle.AddParameterPresentCondition(False, "table.border.bottom.style", False)

        ucrChkTableBottomWidth.SetText("Bottom border Width")
        ucrNudTableBottomWidth.SetParameter(New RParameter("table.border.bottom.width"))
        ucrNudTableBottomWidth.SetRDefault(0)
        ucrChkTableBottomWidth.AddParameterPresentCondition(True, "table.border.bottom.width")
        ucrChkTableBottomWidth.AddParameterPresentCondition(False, "table.border.bottom.width", False)

        ucrChkTableBottomColor.SetText("Bottom border color")
        ucrInputTableBottomColor.SetParameter(New RParameter("table.border.bottom.color"))
        ucrChkTableBottomColor.AddParameterPresentCondition(True, "table.border.bottom.color")
        ucrChkTableBottomColor.AddParameterPresentCondition(False, "table.border.bottom.color", False)

        ucrChkTableLeftStyle.SetText("Left border style")
        ucrInputTableLeftStyle.SetParameter(New RParameter("table.border.left.style"))
        ucrInputTableLeftStyle.SetItems(dctBorderStyles)
        ucrChkTableLeftStyle.AddParameterPresentCondition(True, "table.border.left.style")
        ucrChkTableLeftStyle.AddParameterPresentCondition(False, "table.border.left.style", False)

        ucrChkTableLeftWidth.SetText("Left border Width")
        ucrNudTableLeftWidth.SetParameter(New RParameter("table.border.left.width"))
        ucrNudTableLeftWidth.SetRDefault(0)
        ucrChkTableLeftWidth.AddParameterPresentCondition(True, "table.border.left.width")
        ucrChkTableLeftWidth.AddParameterPresentCondition(False, "table.border.left.width", False)

        ucrChkTableLeftColor.SetText("Left border color")
        ucrInputTableLeftColor.SetParameter(New RParameter("table.border.left.color"))
        ucrChkTableLeftColor.AddParameterPresentCondition(True, "table.border.left.color")
        ucrChkTableLeftColor.AddParameterPresentCondition(False, "table.border.left.color", False)

        ucrChkTableWidth.AddToLinkedControls(ucrNudTableWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkTableLayout.AddToLinkedControls(ucrInputTableLayout, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableAlign.AddToLinkedControls(ucrInputTableAlign, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableBackColor.AddToLinkedControls(ucrTableBackgroundColors, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkTableFontNames.AddToLinkedControls(ucrInputTableFontNames, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableFontSize.AddToLinkedControls(ucrNudTableFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkTableFontWeight.AddToLinkedControls(ucrInputTableFontWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableFontStyle.AddToLinkedControls(ucrInputTableFontStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableFontColor.AddToLinkedControls(ucrInputTableFontColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkTableTopColor.AddToLinkedControls(ucrInputTableTopColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkTableTopStyle.AddToLinkedControls(ucrInputTableTopStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableTopWidth.AddToLinkedControls(ucrNudTableTopWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkTableRightColor.AddToLinkedControls(ucrInputTableRightColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkTableRightStyle.AddToLinkedControls(ucrInputTableRightStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableRightWidth.AddToLinkedControls(ucrNudTableRightWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkTableBottomColor.AddToLinkedControls(ucrInputTableBottomColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkTableBottomStyle.AddToLinkedControls(ucrInputTableBottomStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableBottomWidth.AddToLinkedControls(ucrNudTableBottomWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkTableLeftColor.AddToLinkedControls(ucrInputTableLeftColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkTableLeftStyle.AddToLinkedControls(ucrInputTableLeftStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableLeftWidth.AddToLinkedControls(ucrNudTableLeftWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)

        ucrChkColumnsBackColor.SetText("Background Color")
        ucrInputColumnsBackColor.SetParameter(New RParameter("column_labels.background.color"))
        ucrChkColumnsBackColor.AddParameterPresentCondition(True, "column_labels.background.color")
        ucrChkColumnsBackColor.AddParameterPresentCondition(False, "column_labels.background.color", False)

        ucrChkColumnsPadding.SetText("Vertical Padding")
        ucrNudColumnsPadding.SetParameter(New RParameter("column_labels.padding"))
        ucrNudColumnsPadding.SetRDefault(0)
        ucrChkColumnsPadding.AddParameterPresentCondition(True, "column_labels.padding")
        ucrChkColumnsPadding.AddParameterPresentCondition(False, "column_labels.padding", False)

        ucrChkColumnsFontSize.SetText("Font Size")
        ucrNudColumnsFontSize.SetParameter(New RParameter("column_labels.font.size"))
        ucrNudColumnsFontSize.SetRDefault(0)
        ucrChkColumnsFontSize.AddParameterPresentCondition(True, "column_labels.font.size")
        ucrChkColumnsFontSize.AddParameterPresentCondition(False, "column_labels.font.size", False)

        ucrChkColumnsHorizontalPadding.SetText("Horizontal Padding")
        ucrNudColumnsHorizontalPadding.SetParameter(New RParameter("column_labels.padding.horizontal"))
        ucrNudColumnsHorizontalPadding.SetRDefault(0)
        ucrChkColumnsHorizontalPadding.AddParameterPresentCondition(True, "column_labels.padding.horizontal")
        ucrChkColumnsHorizontalPadding.AddParameterPresentCondition(False, "column_labels.padding.horizontal", False)

        ucrChkColumnsFontWeight.SetText("Font Weights")
        ucrInputColumnsFontWeight.SetParameter(New RParameter("column_labels.font.weight"))
        ucrInputColumnsFontWeight.SetItems(dctWeights)
        ucrChkColumnsFontWeight.AddParameterPresentCondition(True, "column_labels.font.weight")
        ucrChkColumnsFontWeight.AddParameterPresentCondition(False, "column_labels.font.weight", False)

        ucrChkColumnsTextTransform.SetText("Text Transform")
        ucrInputColumnsTextTransform.SetParameter(New RParameter("column_labels.text_transform"))
        ucrInputColumnsTextTransform.SetItems(dctTextTransform)
        ucrChkColumnsTextTransform.AddParameterPresentCondition(True, "column_labels.text_transform")
        ucrChkColumnsTextTransform.AddParameterPresentCondition(False, "column_labels.text_transform", False)

        ucrChkColumnsVlineWidth.SetText("Vlines Width")
        ucrNudColumnsVlineWidth.SetParameter(New RParameter("column_labels.vlines.width"))
        ucrNudColumnsVlineWidth.SetRDefault(0)
        ucrChkColumnsVlineWidth.AddParameterPresentCondition(True, "column_labels.vlines.width")
        ucrChkColumnsVlineWidth.AddParameterPresentCondition(False, "column_labels.vlines.width", False)

        ucrChkColumnsVlineStyle.SetText("Vlines Style")
        ucrInputColumnsVlineStyle.SetParameter(New RParameter("column_labels.vlines.style"))
        ucrInputColumnsVlineStyle.SetItems(dctBorderStyles)
        ucrChkColumnsVlineStyle.AddParameterPresentCondition(True, "column_labels.vlines.style")
        ucrChkColumnsVlineStyle.AddParameterPresentCondition(False, "column_labels.vlines.style", False)

        ucrChkColumnsVlineColor.SetText("Vlines Color")
        ucrInputColumnsVlineColor.SetParameter(New RParameter("column_labels.vlines.color"))
        ucrChkColumnsVlineColor.AddParameterPresentCondition(True, "column_labels.vlines.color")
        ucrChkColumnsVlineColor.AddParameterPresentCondition(False, "column_labels.vlines.color", False)

        ucrChkColumnsTopWidth.SetText("Top Width")
        ucrNudColumnsTopWidth.SetParameter(New RParameter("column_labels.border.top.width"))
        ucrNudColumnsTopWidth.SetRDefault(0)
        ucrChkColumnsTopWidth.AddParameterPresentCondition(True, "column_labels.border.top.width")
        ucrChkColumnsTopWidth.AddParameterPresentCondition(False, "column_labels.border.top.width", False)

        ucrChkColumnsTopStyle.SetText("Top Style")
        ucrInputColumnsTopStyle.SetParameter(New RParameter("column_labels.border.top.style"))
        ucrInputColumnsTopStyle.SetItems(dctBorderStyles)
        ucrChkColumnsTopStyle.AddParameterPresentCondition(True, "column_labels.border.top.style")
        ucrChkColumnsTopStyle.AddParameterPresentCondition(False, "column_labels.border.top.style", False)

        ucrChkColomnsTopColor.SetText("Top Color")
        ucrInputColumnsTopColor.SetParameter(New RParameter("column_labels.border.top.color"))
        ucrChkColomnsTopColor.AddParameterPresentCondition(True, "column_labels.border.top.color")
        ucrChkColomnsTopColor.AddParameterPresentCondition(False, "column_labels.border.top.color", False)

        ucrChkColumnsBottomWidth.SetText("Bottom Width")
        ucrNudColumnsBottomWidth.SetParameter(New RParameter("column_labels.border.bottom.width"))
        ucrNudColumnsBottomWidth.SetRDefault(0)
        ucrChkColumnsBottomWidth.AddParameterPresentCondition(True, "column_labels.border.bottom.width")
        ucrChkColumnsBottomWidth.AddParameterPresentCondition(False, "column_labels.border.bottom.width", False)

        ucrChkColumnsBottomStyle.SetText("Bottom Style")
        ucrInputColumnsBottomStyle.SetParameter(New RParameter("column_labels.border.bottom.style"))
        ucrInputColumnsBottomStyle.SetItems(dctBorderStyles)
        ucrChkColumnsBottomStyle.AddParameterPresentCondition(True, "column_labels.border.bottom.style")
        ucrChkColumnsBottomStyle.AddParameterPresentCondition(False, "column_labels.border.bottom.style", False)

        ucrChkColumnsBottomColor.SetText("Bottom Color")
        ucrInputColumnsBottomColor.SetParameter(New RParameter("column_labels.border.bottom.color"))
        ucrChkColumnsBottomColor.AddParameterPresentCondition(True, "column_labels.border.bottom.color")
        ucrChkColumnsBottomColor.AddParameterPresentCondition(False, "column_labels.border.bottom.color", False)

        ucrChkColumnsSideWidth.SetText("Side Width")
        ucrNudColumnsSideWidth.SetParameter(New RParameter("column_labels.border.lr.width"))
        ucrNudColumnsSideWidth.SetRDefault(0)
        ucrChkColumnsSideWidth.AddParameterPresentCondition(True, "column_labels.border.lr.width")
        ucrChkColumnsSideWidth.AddParameterPresentCondition(False, "column_labels.border.lr.width", False)

        ucrChkColumnsSideStyle.SetText("Side Style")
        ucrInputColumnsSideStyle.SetParameter(New RParameter("column_labels.border.lr.style"))
        ucrInputColumnsSideStyle.SetItems(dctBorderStyles)
        ucrChkColumnsSideStyle.AddParameterPresentCondition(True, "column_labels.border.lr.style")
        ucrChkColumnsSideStyle.AddParameterPresentCondition(False, "column_labels.border.lr.style", False)

        ucrChkColumnsSideColor.SetText("Side Color")
        ucrInputColumnsSideColor.SetParameter(New RParameter("column_labels.border.lr.colour"))
        ucrChkColumnsSideColor.AddParameterPresentCondition(True, "column_labels.border.lr.colour")
        ucrChkColumnsSideColor.AddParameterPresentCondition(False, "column_labels.border.lr.colour", False)

        ucrChkColumnsBackColor.AddToLinkedControls(ucrInputColumnsBackColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkColumnsTextTransform.AddToLinkedControls(ucrInputColumnsTextTransform, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsFontSize.AddToLinkedControls(ucrNudColumnsFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsFontWeight.AddToLinkedControls(ucrInputColumnsFontWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsPadding.AddToLinkedControls(ucrNudColumnsPadding, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsHorizontalPadding.AddToLinkedControls(ucrNudColumnsHorizontalPadding, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsVlineWidth.AddToLinkedControls(ucrNudColumnsVlineWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsVlineStyle.AddToLinkedControls(ucrInputColumnsVlineStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsVlineColor.AddToLinkedControls(ucrInputColumnsVlineColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkColumnsBottomWidth.AddToLinkedControls(ucrNudColumnsBottomWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsBottomStyle.AddToLinkedControls(ucrInputColumnsBottomStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsBottomColor.AddToLinkedControls(ucrInputColumnsBottomColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkColumnsSideWidth.AddToLinkedControls(ucrNudColumnsSideWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsSideStyle.AddToLinkedControls(ucrInputColumnsSideStyle, {True}, bNewLinkedHideIfParameterMissing:=True, bNewLinkedAddRemoveParameter:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsSideColor.AddToLinkedControls(ucrInputColumnsSideColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")
        ucrChkColumnsTopWidth.AddToLinkedControls(ucrNudColumnsTopWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsTopStyle.AddToLinkedControls(ucrInputColumnsTopStyle, {True}, bNewLinkedHideIfParameterMissing:=True, bNewLinkedAddRemoveParameter:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColomnsTopColor.AddToLinkedControls(ucrInputColumnsTopColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="Black")

    End Sub

    Public Sub SetRCode(bReset As Boolean, clsNewThemesTabOption As RFunction)
        bRCodeSet = False
        clsThemesTabOptionsFunction = clsNewThemesTabOption

        If Not bControlsInitialised Then
            InitialiseControls()
        End If

        ucrChkBackgroundColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputBackgroundColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkAlignment.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputAlignment.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSubTitleSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudSubTitleSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSubTitleWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSubTitleWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkBoxLength.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudBoxLength.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkBoxWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudBoxWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkBottomColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputBottomColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSideColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSideColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableAlign.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableAlign.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrTableBackgroundColors.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableFontColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableFontColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableLayout.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableLayout.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableFontNames.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableFontNames.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableFontStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableFontStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableTopColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableTopColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableTopStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableTopStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableTopWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableTopWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableRightColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableRightColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableRightStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableRightStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableRightWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableRightWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableLeftColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableLeftColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableLeftStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableLeftStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableLeftWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableLeftWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsHorizontalPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsHorizontalPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsTextTransform.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsTextTransform.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColomnsTopColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsTopColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsTopStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsTopStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsTopWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsTopWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsVlineColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsVlineColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsVlineStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsVlineStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsVlineWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsVlineWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsSideColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsSideColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
    End Sub

End Class