' R- Instat
' Copyright (C) 2015-2017
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License 
' along with this program.  If not, see <http://www.gnu.org/licenses/>.

Imports instat.Translations

Public Class sdgSummaryThemes
    Private clsThemesTabOptionsFunction As New RFunction
    Private bRCodeSet As Boolean = False
    Private bControlsInitialised As Boolean = False

    Private Sub sdgSummaryThemes_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        autoTranslate(Me)
    End Sub

    Private Sub InitialiseControls()
        Dim dctAlignment, dctWeights, dctStyles, dctBorderStyles, dctTextTransform, dctLayouts, dctFontNames, dctFootnotesMarks,
        dctFootnotesMultiline, dctSeparators As New Dictionary(Of String, String)

        dctWeights.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctWeights.Add("Normal", Chr(34) & "normal" & Chr(34))
        dctWeights.Add("Bold", Chr(34) & "bold" & Chr(34))
        dctWeights.Add("Lighter", Chr(34) & "lighter" & Chr(34))
        dctWeights.Add("Bolder", Chr(34) & "bolder" & Chr(34))

        dctAlignment.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctAlignment.Add("Left", Chr(34) & "left" & Chr(34))
        dctAlignment.Add("Right", Chr(34) & "right" & Chr(34))
        dctAlignment.Add("Center", Chr(34) & "center" & Chr(34))

        dctStyles.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctStyles.Add("Normal", Chr(34) & "normal" & Chr(34))
        dctStyles.Add("Italic", Chr(34) & "italic" & Chr(34))
        dctStyles.Add("Oblique", Chr(34) & "oblique" & Chr(34))

        dctBorderStyles.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctBorderStyles.Add("Solid", Chr(34) & "solid" & Chr(34))
        dctBorderStyles.Add("Dashed", Chr(34) & "dashed" & Chr(34))
        dctBorderStyles.Add("Dotted", Chr(34) & "dotted" & Chr(34))

        dctTextTransform.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctTextTransform.Add("Uppercase", Chr(34) & "uppercase" & Chr(34))
        dctTextTransform.Add("Lowercase", Chr(34) & "lowercase" & Chr(34))
        dctTextTransform.Add("Capitalize", Chr(34) & "capitalize" & Chr(34))

        dctLayouts.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctLayouts.Add("Auto", Chr(34) & "auto" & Chr(34))
        dctLayouts.Add("Fixed", Chr(34) & "fixed" & Chr(34))

        dctFontNames.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctFontNames.Add("Apple system", Chr(34) & "-apple-system" & Chr(34))
        dctFontNames.Add("Cantarell", Chr(34) & "Cantarell" & Chr(34))
        dctFontNames.Add("Helvetica Neue", Chr(34) & "Helvetica Neue" & Chr(34))
        dctFontNames.Add("BlinkMacSystemFont", Chr(34) & "BlinkMacSystemFont" & Chr(34))
        dctFontNames.Add("Ubuntu", Chr(34) & "Ubuntu" & Chr(34))
        dctFontNames.Add("Fira Sans", Chr(34) & "Fira Sans" & Chr(34))
        dctFontNames.Add("Segoe UI", Chr(34) & "Segoe UI" & Chr(34))
        dctFontNames.Add("Roboto", Chr(34) & "Roboto" & Chr(34))
        dctFontNames.Add("Oxygen", Chr(34) & "Oxygen" & Chr(34))
        dctFontNames.Add("Droid Sans", Chr(34) & "Droid Sans" & Chr(34))
        dctFontNames.Add("Arial", Chr(34) & "Arial" & Chr(34))
        dctFontNames.Add("Sans-serif", Chr(34) & "Sans-serif" & Chr(34))

        dctFootnotesMarks.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctFootnotesMarks.Add("Numbers", Chr(34) & "numbers" & Chr(34))
        dctFootnotesMarks.Add("letters", Chr(34) & "letters" & Chr(34))
        dctFootnotesMarks.Add("LETTERS", Chr(34) & "LETTERS" & Chr(34))
        dctFootnotesMarks.Add("Standard", Chr(34) & "standard" & Chr(34))
        dctFootnotesMarks.Add("Extended", Chr(34) & "extended" & Chr(34))

        dctFootnotesMultiline.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctFootnotesMultiline.Add("True", "TRUE")
        dctFootnotesMultiline.Add("False", "FALSE")

        dctSeparators.Add("NULL", Chr(34) & "NULL" & Chr(34))
        dctSeparators.Add("Space", "  ")
        dctSeparators.Add("Semi-colon ", " ; ")
        dctSeparators.Add("Colon", " : ")
        dctSeparators.Add("Comma", " , ")
        dctSeparators.Add("Dash", "-")

        'Titles
        ucrChkBackgroundColour.SetText("Background Colour")
        ucrInputBackgroundColour.SetParameter(New RParameter("heading.background.color"))
        ucrChkBackgroundColour.AddParameterPresentCondition(True, "heading.background.color")
        ucrChkBackgroundColour.AddParameterPresentCondition(False, "heading.background.color", False)

        ucrChkAlignment.SetText("Alignment")
        ucrInputAlignment.SetParameter(New RParameter("heading.align"))
        ucrInputAlignment.SetItems(dctAlignment)
        ucrChkAlignment.AddParameterPresentCondition(True, "heading.align")
        ucrChkAlignment.AddParameterPresentCondition(False, "heading.align", False)

        ucrChkFontSize.SetText("Font Size")
        ucrNudFontSize.SetParameter(New RParameter("heading.title.font.size"))
        ucrNudFontSize.SetRDefault(0)
        ucrChkFontSize.AddParameterPresentCondition(True, "heading.title.font.size")
        ucrChkFontSize.AddParameterPresentCondition(False, "heading.title.font.size", False)

        ucrChkSubTitleSize.SetText("Font Size")
        ucrNudSubTitleSize.SetParameter(New RParameter("heading.subtitle.font.size"))
        ucrNudSubTitleSize.SetRDefault(0)
        ucrChkSubTitleSize.AddParameterPresentCondition(True, "heading.subtitle.font.size")
        ucrChkSubTitleSize.AddParameterPresentCondition(False, "heading.subtitle.font.size", False)

        ucrChkFontWeight.SetText("Font Weights")
        ucrInputFontWeight.SetParameter(New RParameter("heading.title.font.weight"))
        ucrInputFontWeight.SetItems(dctWeights)
        ucrChkFontWeight.AddParameterPresentCondition(True, "heading.title.font.weight")
        ucrChkFontWeight.AddParameterPresentCondition(False, "heading.title.font.weight", False)

        ucrChkSubTitleWeight.SetText("Font Weights")
        ucrInputSubTitleWeight.SetParameter(New RParameter("heading.subtitle.font.weight"))
        ucrInputSubTitleWeight.SetItems(dctWeights)
        ucrChkSubTitleWeight.AddParameterPresentCondition(True, "heading.subtitle.font.weight")
        ucrChkSubTitleWeight.AddParameterPresentCondition(False, "heading.subtitle.font.weight", False)

        ucrChkBoxWidth.SetText("Vertical Padding")
        ucrNudBoxWidth.SetParameter(New RParameter("heading.padding"))
        ucrNudBoxWidth.SetRDefault(0)
        ucrChkBoxWidth.AddParameterPresentCondition(True, "heading.padding")
        ucrChkBoxWidth.AddParameterPresentCondition(False, "heading.padding", False)

        ucrChkBoxLength.SetText("Horizontal Padding")
        ucrNudBoxLength.SetParameter(New RParameter("heading.padding.horizontal"))
        ucrNudBoxLength.SetRDefault(0)
        ucrChkBoxLength.AddParameterPresentCondition(True, "heading.padding.horizontal")
        ucrChkBoxLength.AddParameterPresentCondition(False, "heading.padding,horizontal", False)

        ucrChkBottomWidth.SetText("Bottom Width")
        ucrNudBottomWidth.SetParameter(New RParameter("heading.border.bottom.width"))
        ucrNudBottomWidth.SetRDefault(0)
        ucrChkBottomWidth.AddParameterPresentCondition(True, "heading.border.bottom.width")
        ucrChkBottomWidth.AddParameterPresentCondition(False, "heading.border.bottom.width", False)

        ucrChkBottomStyle.SetText("Bottom Style")
        ucrInputBottomStyle.SetParameter(New RParameter("heading.border.bottom.style"))
        ucrInputBottomStyle.SetItems(dctBorderStyles)
        ucrChkBottomStyle.AddParameterPresentCondition(True, "heading.border.bottom.style")
        ucrChkBottomStyle.AddParameterPresentCondition(False, "heading.border.bottom.style", False)

        ucrChkBottomColour.SetText("Bottom Color")
        ucrInputBottomColour.SetParameter(New RParameter("heading.border.bottom.color"))
        ucrChkBottomColour.AddParameterPresentCondition(True, "heading.border.bottom.color")
        ucrChkBottomColour.AddParameterPresentCondition(False, "heading.border.bottom.color", False)

        ucrChkSideWidth.SetText("Side Width")
        ucrNudSideWidth.SetParameter(New RParameter("heading.border.lr.width"))
        ucrNudSideWidth.SetRDefault(0)
        ucrChkSideWidth.AddParameterPresentCondition(True, "heading.border.lr.width")
        ucrChkSideWidth.AddParameterPresentCondition(False, "heading.border.lr.width", False)

        ucrChkSideStyle.SetText("Side Style")
        ucrInputSideStyle.SetParameter(New RParameter("heading.border.lr.style"))
        ucrInputSideStyle.SetItems(dctBorderStyles)
        ucrChkSideStyle.AddParameterPresentCondition(True, "heading.border.lr.style")
        ucrChkSideStyle.AddParameterPresentCondition(False, "heading.border.lr.style", False)

        ucrChkSideColour.SetText("Side Color")
        ucrInputSideColour.SetParameter(New RParameter("heading.border.lr.color"))
        ucrChkSideColour.AddParameterPresentCondition(True, "heading.border.lr.color")
        ucrChkSideColour.AddParameterPresentCondition(False, "heading.border.lr.color", False)

        ucrChkBackgroundColour.AddToLinkedControls(ucrInputBackgroundColour, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkAlignment.AddToLinkedControls(ucrInputAlignment, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkFontSize.AddToLinkedControls(ucrNudFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkFontWeight.AddToLinkedControls(ucrInputFontWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="null")
        ucrChkSubTitleSize.AddToLinkedControls(ucrNudSubTitleSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkSubTitleWeight.AddToLinkedControls(ucrInputSubTitleWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkBoxWidth.AddToLinkedControls(ucrNudBoxWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkBoxLength.AddToLinkedControls(ucrNudBoxLength, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkBottomWidth.AddToLinkedControls(ucrNudBottomWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkBottomStyle.AddToLinkedControls(ucrInputBottomStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkBottomColour.AddToLinkedControls(ucrInputBottomColour, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkSideWidth.AddToLinkedControls(ucrNudSideWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkSideStyle.AddToLinkedControls(ucrInputSideStyle, {True}, bNewLinkedHideIfParameterMissing:=True, bNewLinkedAddRemoveParameter:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkSideColour.AddToLinkedControls(ucrInputSideColour, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        'Tables
        ucrChkTableWidth.SetText("Width")
        ucrInputTableFontWeight.SetParameter(New RParameter("table.width"))
        ucrChkTableWidth.AddParameterPresentCondition(True, "table.width")
        ucrChkTableWidth.AddParameterPresentCondition(False, "table.width", False)

        ucrChkTableLayout.SetText("Layout")
        ucrInputTableLayout.SetParameter(New RParameter("table.layout"))
        ucrInputTableLayout.SetItems(dctLayouts)
        ucrChkTableLayout.AddParameterPresentCondition(True, "table.layout")
        ucrChkTableLayout.AddParameterPresentCondition(False, "table.layout", False)

        ucrChkTableAlign.SetText("Alignment")
        ucrInputTableAlign.SetParameter(New RParameter("table.align"))
        ucrInputTableAlign.SetItems(dctAlignment)
        ucrChkTableAlign.AddParameterPresentCondition(True, "table.align")
        ucrChkTableAlign.AddParameterPresentCondition(False, "table.align", False)

        ucrChkTableBackColor.SetText("Background Color")
        ucrTableBackgroundColors.SetParameter(New RParameter("table.background.color"))
        ucrChkTableBackColor.AddParameterPresentCondition(True, "table.background.color")
        ucrChkTableBackColor.AddParameterPresentCondition(False, "table.background.color", False)

        ucrChkTableFontNames.SetText("Font Names")
        ucrInputTableFontNames.SetParameter(New RParameter("table.font.names"))
        ucrInputTableFontNames.SetItems(dctFontNames)
        ucrChkTableFontNames.AddParameterPresentCondition(True, "table.font.names")
        ucrChkTableFontNames.AddParameterPresentCondition(False, "table.font.names", False)

        ucrChkTableFontSize.SetText("Font Size")
        ucrNudTableFontSize.SetParameter(New RParameter("table.font.size"))
        ucrNudTableFontSize.SetRDefault(0)
        ucrChkTableFontSize.AddParameterPresentCondition(True, "table.font.size")
        ucrChkTableFontSize.AddParameterPresentCondition(False, "table.font.size", False)

        ucrChkTableFontWeight.SetText("Font Weight")
        ucrInputTableFontWeight.SetParameter(New RParameter("table.font.weight"))
        ucrInputTableFontWeight.SetItems(dctWeights)
        ucrChkTableFontWeight.AddParameterPresentCondition(True, "table.font.weight")
        ucrChkTableFontWeight.AddParameterPresentCondition(False, "table.font.weight", False)

        ucrChkTableFontStyle.SetText("Font Style")
        ucrInputTableFontStyle.SetParameter(New RParameter("table.font.style"))
        ucrInputTableFontStyle.SetItems(dctStyles)
        ucrChkTableFontStyle.AddParameterPresentCondition(True, "table.font.style")
        ucrChkTableFontStyle.AddParameterPresentCondition(False, "table.font.style", False)

        ucrChkTableFontColor.SetText("Font Color")
        ucrInputTableFontColor.SetParameter(New RParameter("table.font.color"))
        ucrChkTableFontColor.AddParameterPresentCondition(True, "table.font.color")
        ucrChkTableFontColor.AddParameterPresentCondition(False, "table.font.color", False)

        ucrChkTableTopStyle.SetText("Top Style")
        ucrInputTableTopStyle.SetParameter(New RParameter("table.border.top.style"))
        ucrInputTableTopStyle.SetItems(dctBorderStyles)
        ucrChkTableTopStyle.AddParameterPresentCondition(True, "table.border.top.style")
        ucrChkTableTopStyle.AddParameterPresentCondition(False, "table.border.top.style", False)

        ucrChkTableTopWidth.SetText("Top Width")
        ucrNudTableTopWidth.SetParameter(New RParameter("table.border.top.width"))
        ucrNudTableTopWidth.SetRDefault(0)
        ucrChkTableTopWidth.AddParameterPresentCondition(True, "table.border.top.width")
        ucrChkTableTopWidth.AddParameterPresentCondition(False, "table.border.top.width", False)

        ucrChkTableTopColor.SetText("Top Color")
        ucrInputTableTopColor.SetParameter(New RParameter("table.border.top.color"))
        ucrChkTableTopColor.AddParameterPresentCondition(True, "table.border.top.color")
        ucrChkTableTopColor.AddParameterPresentCondition(False, "table.border.top.color", False)

        ucrChkTableRightStyle.SetText("Right Style")
        ucrInputTableRightStyle.SetParameter(New RParameter("table.border.right.style"))
        ucrInputTableRightStyle.SetItems(dctBorderStyles)
        ucrChkTableRightStyle.AddParameterPresentCondition(True, "table.border.right.style")
        ucrChkTableRightStyle.AddParameterPresentCondition(False, "table.border.right.style", False)

        ucrChkTableRightWidth.SetText("Right Width")
        ucrNudTableRightWidth.SetParameter(New RParameter("table.border.right.width"))
        ucrNudTableRightWidth.SetRDefault(0)
        ucrChkTableRightWidth.AddParameterPresentCondition(True, "table.border.right.width")
        ucrChkTableRightWidth.AddParameterPresentCondition(False, "table.border.right.width", False)

        ucrChkTableRightColor.SetText("Right Color")
        ucrInputTableRightColor.SetParameter(New RParameter("table.border.right.color"))
        ucrChkTableRightColor.AddParameterPresentCondition(True, "table.border.right.color")
        ucrChkTableRightColor.AddParameterPresentCondition(False, "table.border.right.color", False)

        ucrChkTableBottomStyle.SetText("Bottom Style")
        ucrInputTableBottomStyle.SetParameter(New RParameter("table.border.bottom.style"))
        ucrInputTableBottomStyle.SetItems(dctBorderStyles)
        ucrChkTableBottomStyle.AddParameterPresentCondition(True, "table.border.bottom.style")
        ucrChkTableBottomStyle.AddParameterPresentCondition(False, "table.border.bottom.style", False)

        ucrChkTableBottomWidth.SetText("Bottom Width")
        ucrNudTableBottomWidth.SetParameter(New RParameter("table.border.bottom.width"))
        ucrNudTableBottomWidth.SetRDefault(0)
        ucrChkTableBottomWidth.AddParameterPresentCondition(True, "table.border.bottom.width")
        ucrChkTableBottomWidth.AddParameterPresentCondition(False, "table.border.bottom.width", False)

        ucrChkTableBottomColor.SetText("Bottom Color")
        ucrInputTableBottomColor.SetParameter(New RParameter("table.border.bottom.color"))
        ucrChkTableBottomColor.AddParameterPresentCondition(True, "table.border.bottom.color")
        ucrChkTableBottomColor.AddParameterPresentCondition(False, "table.border.bottom.color", False)

        ucrChkTableLeftStyle.SetText("Left Style")
        ucrInputTableLeftStyle.SetParameter(New RParameter("table.border.left.style"))
        ucrInputTableLeftStyle.SetItems(dctBorderStyles)
        ucrChkTableLeftStyle.AddParameterPresentCondition(True, "table.border.left.style")
        ucrChkTableLeftStyle.AddParameterPresentCondition(False, "table.border.left.style", False)

        ucrChkTableLeftWidth.SetText("Left Width")
        ucrNudTableLeftWidth.SetParameter(New RParameter("table.border.left.width"))
        ucrNudTableLeftWidth.SetRDefault(0)
        ucrChkTableLeftWidth.AddParameterPresentCondition(True, "table.border.left.width")
        ucrChkTableLeftWidth.AddParameterPresentCondition(False, "table.border.left.width", False)

        ucrChkTableLeftColor.SetText("Left Color")
        ucrInputTableLeftColor.SetParameter(New RParameter("table.border.left.color"))
        ucrChkTableLeftColor.AddParameterPresentCondition(True, "table.border.left.color")
        ucrChkTableLeftColor.AddParameterPresentCondition(False, "table.border.left.color", False)

        ucrChkTableWidth.AddToLinkedControls(ucrNudTableWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkTableLayout.AddToLinkedControls(ucrInputTableLayout, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableAlign.AddToLinkedControls(ucrInputTableAlign, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableBackColor.AddToLinkedControls(ucrTableBackgroundColors, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NUL")
        ucrChkTableFontNames.AddToLinkedControls(ucrInputTableFontNames, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableFontSize.AddToLinkedControls(ucrNudTableFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkTableFontWeight.AddToLinkedControls(ucrInputTableFontWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableFontStyle.AddToLinkedControls(ucrInputTableFontStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableFontColor.AddToLinkedControls(ucrInputTableFontColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableTopColor.AddToLinkedControls(ucrInputTableTopColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableTopStyle.AddToLinkedControls(ucrInputTableTopStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableTopWidth.AddToLinkedControls(ucrNudTableTopWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkTableRightColor.AddToLinkedControls(ucrInputTableRightColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableRightStyle.AddToLinkedControls(ucrInputTableRightStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableRightWidth.AddToLinkedControls(ucrNudTableRightWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkTableBottomColor.AddToLinkedControls(ucrInputTableBottomColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableBottomStyle.AddToLinkedControls(ucrInputTableBottomStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableBottomWidth.AddToLinkedControls(ucrNudTableBottomWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkTableLeftColor.AddToLinkedControls(ucrInputTableLeftColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableLeftStyle.AddToLinkedControls(ucrInputTableLeftStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkTableLeftWidth.AddToLinkedControls(ucrNudTableLeftWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        'Columns
        ucrChkColumnsBackColor.SetText("Background Color")
        ucrInputColumnsBackColor.SetParameter(New RParameter("column_labels.background.color"))
        ucrChkColumnsBackColor.AddParameterPresentCondition(True, "column_labels.background.color")
        ucrChkColumnsBackColor.AddParameterPresentCondition(False, "column_labels.background.color", False)

        ucrChkColumnsPadding.SetText("Vertical Padding")
        ucrNudColumnsPadding.SetParameter(New RParameter("column_labels.padding"))
        ucrNudColumnsPadding.SetRDefault(0)
        ucrChkColumnsPadding.AddParameterPresentCondition(True, "column_labels.padding")
        ucrChkColumnsPadding.AddParameterPresentCondition(False, "column_labels.padding", False)

        ucrChkColumnsFontSize.SetText("Font Size")
        ucrNudColumnsFontSize.SetParameter(New RParameter("column_labels.font.size"))
        ucrNudColumnsFontSize.SetRDefault(0)
        ucrChkColumnsFontSize.AddParameterPresentCondition(True, "column_labels.font.size")
        ucrChkColumnsFontSize.AddParameterPresentCondition(False, "column_labels.font.size", False)

        ucrChkColumnsHorizontalPadding.SetText("Horizontal Padding")
        ucrNudColumnsHorizontalPadding.SetParameter(New RParameter("column_labels.padding.horizontal"))
        ucrNudColumnsHorizontalPadding.SetRDefault(0)
        ucrChkColumnsHorizontalPadding.AddParameterPresentCondition(True, "column_labels.padding.horizontal")
        ucrChkColumnsHorizontalPadding.AddParameterPresentCondition(False, "column_labels.padding.horizontal", False)

        ucrChkColumnsFontWeight.SetText("Font Weights")
        ucrInputColumnsFontWeight.SetParameter(New RParameter("column_labels.font.weight"))
        ucrInputColumnsFontWeight.SetItems(dctWeights)
        ucrChkColumnsFontWeight.AddParameterPresentCondition(True, "column_labels.font.weight")
        ucrChkColumnsFontWeight.AddParameterPresentCondition(False, "column_labels.font.weight", False)

        ucrChkColumnsTextTransform.SetText("Text Transform")
        ucrInputColumnsTextTransform.SetParameter(New RParameter("column_labels.text_transform"))
        ucrInputColumnsTextTransform.SetItems(dctTextTransform)
        ucrChkColumnsTextTransform.AddParameterPresentCondition(True, "column_labels.text_transform")
        ucrChkColumnsTextTransform.AddParameterPresentCondition(False, "column_labels.text_transform", False)

        ucrChkColumnsVlineWidth.SetText("Vlines Width")
        ucrNudColumnsVlineWidth.SetParameter(New RParameter("column_labels.vlines.width"))
        ucrNudColumnsVlineWidth.SetRDefault(0)
        ucrChkColumnsVlineWidth.AddParameterPresentCondition(True, "column_labels.vlines.width")
        ucrChkColumnsVlineWidth.AddParameterPresentCondition(False, "column_labels.vlines.width", False)

        ucrChkColumnsVlineStyle.SetText("Vlines Style")
        ucrInputColumnsVlineStyle.SetParameter(New RParameter("column_labels.vlines.style"))
        ucrInputColumnsVlineStyle.SetItems(dctBorderStyles)
        ucrChkColumnsVlineStyle.AddParameterPresentCondition(True, "column_labels.vlines.style")
        ucrChkColumnsVlineStyle.AddParameterPresentCondition(False, "column_labels.vlines.style", False)

        ucrChkColumnsVlineColor.SetText("Vlines Color")
        ucrInputColumnsVlineColor.SetParameter(New RParameter("column_labels.vlines.color"))
        ucrChkColumnsVlineColor.AddParameterPresentCondition(True, "column_labels.vlines.color")
        ucrChkColumnsVlineColor.AddParameterPresentCondition(False, "column_labels.vlines.color", False)

        ucrChkColumnsTopWidth.SetText("Top Width")
        ucrNudColumnsTopWidth.SetParameter(New RParameter("column_labels.border.top.width"))
        ucrNudColumnsTopWidth.SetRDefault(0)
        ucrChkColumnsTopWidth.AddParameterPresentCondition(True, "column_labels.border.top.width")
        ucrChkColumnsTopWidth.AddParameterPresentCondition(False, "column_labels.border.top.width", False)

        ucrChkColumnsTopStyle.SetText("Top Style")
        ucrInputColumnsTopStyle.SetParameter(New RParameter("column_labels.border.top.style"))
        ucrInputColumnsTopStyle.SetItems(dctBorderStyles)
        ucrChkColumnsTopStyle.AddParameterPresentCondition(True, "column_labels.border.top.style")
        ucrChkColumnsTopStyle.AddParameterPresentCondition(False, "column_labels.border.top.style", False)

        ucrChkColomnsTopColor.SetText("Top Color")
        ucrInputColumnsTopColor.SetParameter(New RParameter("column_labels.border.top.color"))
        ucrChkColomnsTopColor.AddParameterPresentCondition(True, "column_labels.border.top.color")
        ucrChkColomnsTopColor.AddParameterPresentCondition(False, "column_labels.border.top.color", False)

        ucrChkColumnsBottomWidth.SetText("Bottom Width")
        ucrNudColumnsBottomWidth.SetParameter(New RParameter("column_labels.border.bottom.width"))
        ucrNudColumnsBottomWidth.SetRDefault(0)
        ucrChkColumnsBottomWidth.AddParameterPresentCondition(True, "column_labels.border.bottom.width")
        ucrChkColumnsBottomWidth.AddParameterPresentCondition(False, "column_labels.border.bottom.width", False)

        ucrChkColumnsBottomStyle.SetText("Bottom Style")
        ucrInputColumnsBottomStyle.SetParameter(New RParameter("column_labels.border.bottom.style"))
        ucrInputColumnsBottomStyle.SetItems(dctBorderStyles)
        ucrChkColumnsBottomStyle.AddParameterPresentCondition(True, "column_labels.border.bottom.style")
        ucrChkColumnsBottomStyle.AddParameterPresentCondition(False, "column_labels.border.bottom.style", False)

        ucrChkColumnsBottomColor.SetText("Bottom Color")
        ucrInputColumnsBottomColor.SetParameter(New RParameter("column_labels.border.bottom.color"))
        ucrChkColumnsBottomColor.AddParameterPresentCondition(True, "column_labels.border.bottom.color")
        ucrChkColumnsBottomColor.AddParameterPresentCondition(False, "column_labels.border.bottom.color", False)

        ucrChkColumnsSideWidth.SetText("Side Width")
        ucrNudColumnsSideWidth.SetParameter(New RParameter("column_labels.border.lr.width"))
        ucrNudColumnsSideWidth.SetRDefault(0)
        ucrChkColumnsSideWidth.AddParameterPresentCondition(True, "column_labels.border.lr.width")
        ucrChkColumnsSideWidth.AddParameterPresentCondition(False, "column_labels.border.lr.width", False)

        ucrChkColumnsSideStyle.SetText("Side Style")
        ucrInputColumnsSideStyle.SetParameter(New RParameter("column_labels.border.lr.style"))
        ucrInputColumnsSideStyle.SetItems(dctBorderStyles)
        ucrChkColumnsSideStyle.AddParameterPresentCondition(True, "column_labels.border.lr.style")
        ucrChkColumnsSideStyle.AddParameterPresentCondition(False, "column_labels.border.lr.style", False)

        ucrChkColumnsSideColor.SetText("Side Color")
        ucrInputColumnsSideColor.SetParameter(New RParameter("column_labels.border.lr.colour"))
        ucrChkColumnsSideColor.AddParameterPresentCondition(True, "column_labels.border.lr.colour")
        ucrChkColumnsSideColor.AddParameterPresentCondition(False, "column_labels.border.lr.colour", False)

        ucrChkColumnsBackColor.AddToLinkedControls(ucrInputColumnsBackColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsTextTransform.AddToLinkedControls(ucrInputColumnsTextTransform, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsFontSize.AddToLinkedControls(ucrNudColumnsFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsFontWeight.AddToLinkedControls(ucrInputColumnsFontWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsPadding.AddToLinkedControls(ucrNudColumnsPadding, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsHorizontalPadding.AddToLinkedControls(ucrNudColumnsHorizontalPadding, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsVlineWidth.AddToLinkedControls(ucrNudColumnsVlineWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsVlineStyle.AddToLinkedControls(ucrInputColumnsVlineStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsVlineColor.AddToLinkedControls(ucrInputColumnsVlineColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsBottomWidth.AddToLinkedControls(ucrNudColumnsBottomWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsBottomStyle.AddToLinkedControls(ucrInputColumnsBottomStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsBottomColor.AddToLinkedControls(ucrInputColumnsBottomColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsSideWidth.AddToLinkedControls(ucrNudColumnsSideWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsSideStyle.AddToLinkedControls(ucrInputColumnsSideStyle, {True}, bNewLinkedHideIfParameterMissing:=True, bNewLinkedAddRemoveParameter:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsSideColor.AddToLinkedControls(ucrInputColumnsSideColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColumnsTopWidth.AddToLinkedControls(ucrNudColumnsTopWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkColumnsTopStyle.AddToLinkedControls(ucrInputColumnsTopStyle, {True}, bNewLinkedHideIfParameterMissing:=True, bNewLinkedAddRemoveParameter:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkColomnsTopColor.AddToLinkedControls(ucrInputColumnsTopColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        'Rows
        ucrChkRowBackColor.SetText("Background Color")
        ucrRowBackColors.SetParameter(New RParameter("row_group.background.color"))
        ucrChkRowBackColor.AddParameterPresentCondition(True, "row_group.background.color")
        ucrChkRowBackColor.AddParameterPresentCondition(False, "row_group.background.color", False)

        ucrChkRowTextTransform.SetText("Text Transform")
        ucrInputRowTextTransform.SetParameter(New RParameter("row_group.text_transform"))
        ucrInputRowTextTransform.SetItems(dctTextTransform)
        ucrChkRowTextTransform.AddParameterPresentCondition(True, "row_group.text_transform")
        ucrChkRowTextTransform.AddParameterPresentCondition(False, "row_group.text_transform", False)

        ucrChkRowGroupPadding.SetText("Vertical Padding")
        ucrNudRowGroupPadding.SetParameter(New RParameter("row_group.padding"))
        ucrNudRowGroupPadding.SetRDefault(0)
        ucrChkRowGroupPadding.AddParameterPresentCondition(True, "row_group.padding")
        ucrChkRowGroupPadding.AddParameterPresentCondition(False, "row_group.padding", False)

        ucrChkRowGroupHorizontalPadding.SetText("Horizontal Padding")
        ucrNudRowGroupHorizontalPadding.SetParameter(New RParameter("row_group.padding.horizontal"))
        ucrNudRowGroupHorizontalPadding.SetRDefault(0)
        ucrChkRowGroupHorizontalPadding.AddParameterPresentCondition(True, "row_group.padding.horizontal")
        ucrChkRowGroupHorizontalPadding.AddParameterPresentCondition(False, "row_group.padding.horizontal", False)

        ucrChkRowFontSize.SetText("Font Size")
        ucrNudRowFontSize.SetParameter(New RParameter("row_group.font.size"))
        ucrNudRowFontSize.SetRDefault(0)
        ucrChkRowFontSize.AddParameterPresentCondition(True, "row_group.font.size")
        ucrChkRowFontSize.AddParameterPresentCondition(False, "row_group.font.size", False)

        ucrChkRowFontWeight.SetText("Font Weight")
        ucrInputRowFontWeight.SetParameter(New RParameter("row_group.font.weight"))
        ucrInputRowFontWeight.SetItems(dctWeights)
        ucrChkRowFontWeight.AddParameterPresentCondition(True, "row_group.font.weight")
        ucrChkRowFontWeight.AddParameterPresentCondition(False, "row_group.font.weight", False)

        ucrChkRowGroupTopStyle.SetText("Top Style")
        ucrInputRowGroupTopStyle.SetParameter(New RParameter("row_group.border.top.style"))
        ucrInputRowGroupTopStyle.SetItems(dctBorderStyles)
        ucrChkRowGroupTopStyle.AddParameterPresentCondition(True, "row_group.border.top.style")
        ucrChkRowGroupTopStyle.AddParameterPresentCondition(False, "row_group.border.top.style", False)

        ucrChkRowGroupTopWidth.SetText("Top Width")
        ucrNudRowGroupTopWidth.SetParameter(New RParameter("row_group.border.top.width"))
        ucrNudRowGroupTopWidth.SetRDefault(0)
        ucrChkRowGroupTopWidth.AddParameterPresentCondition(True, "row_group.border.top.width")
        ucrChkRowGroupTopWidth.AddParameterPresentCondition(False, "row_group.border.top.width", False)

        ucrChkRowGroupTopColor.SetText("Top Color")
        ucrInputRowGroupTopColor.SetParameter(New RParameter("row_group.border.top.color"))
        ucrChkRowGroupTopColor.AddParameterPresentCondition(True, "row_group.border.top.color")
        ucrChkRowGroupTopColor.AddParameterPresentCondition(False, "row_group.border.top.color", False)

        ucrChkRowGroupRightStyle.SetText("Right Style")
        ucrInputRowGroupRightStyle.SetParameter(New RParameter("row_group.border.right.style"))
        ucrInputRowGroupRightStyle.SetItems(dctBorderStyles)
        ucrChkRowGroupRightStyle.AddParameterPresentCondition(True, "row_group.border.right.style")
        ucrChkRowGroupRightStyle.AddParameterPresentCondition(False, "row_group.border.right.style", False)

        ucrChkRowGroupRightWidth.SetText("Right Width")
        ucrNudRowGroupRightWidth.SetParameter(New RParameter("row_group.border.right.width"))
        ucrNudRowGroupRightWidth.SetRDefault(0)
        ucrChkRowGroupRightWidth.AddParameterPresentCondition(True, "row_group.border.right.width")
        ucrChkRowGroupRightWidth.AddParameterPresentCondition(False, "row_group.border.right.width", False)

        ucrChkRowGroupRightColor.SetText("Right Color")
        ucrInputRowGroupRightColor.SetParameter(New RParameter("row_group.border.right.color"))
        ucrChkRowGroupRightColor.AddParameterPresentCondition(True, "row_group.border.right.color")
        ucrChkRowGroupRightColor.AddParameterPresentCondition(False, "row_group.border.right.color", False)

        ucrChkRowGroupBottomStyle.SetText("Bottom Style")
        ucrInputRowGroupBottomStyle.SetParameter(New RParameter("row_group.border.bottom.style"))
        ucrInputRowGroupBottomStyle.SetItems(dctBorderStyles)
        ucrChkRowGroupBottomStyle.AddParameterPresentCondition(True, "row_group.border.bottom.style")
        ucrChkRowGroupBottomStyle.AddParameterPresentCondition(False, "row_group.border.bottom.style", False)

        ucrChkRowGroupBottomWidth.SetText("Bottom Width")
        ucrNudRowGroupBottomWidth.SetParameter(New RParameter("row_group.border.bottom.width"))
        ucrNudTableBottomWidth.SetRDefault(0)
        ucrChkRowGroupBottomWidth.AddParameterPresentCondition(True, "row_group.border.bottom.width")
        ucrChkRowGroupBottomWidth.AddParameterPresentCondition(False, "row_group.border.bottom.width", False)

        ucrChkRowGroupBottomColor.SetText("Bottom Color")
        ucrInputRowGroupBottomColor.SetParameter(New RParameter("row_group.border.bottom.color"))
        ucrChkRowGroupBottomColor.AddParameterPresentCondition(True, "row_group.border.bottom.color")
        ucrChkRowGroupBottomColor.AddParameterPresentCondition(False, "row_group.border.bottom.color", False)

        ucrChkRowGroupLeftStyle.SetText("Left Style")
        ucrInputRowGroupLeftStyle.SetParameter(New RParameter("row_group.border.left.style"))
        ucrInputRowGroupLeftStyle.SetItems(dctBorderStyles)
        ucrChkRowGroupLeftStyle.AddParameterPresentCondition(True, "row_group.border.left.style")
        ucrChkRowGroupLeftStyle.AddParameterPresentCondition(False, "row_group.border.left.style", False)

        ucrChkRowGroupLeftWidth.SetText("Left Width")
        ucrNudRowGroupLeftWidth.SetParameter(New RParameter("row_group.border.left.width"))
        ucrNudRowGroupLeftWidth.SetRDefault(0)
        ucrChkRowGroupLeftWidth.AddParameterPresentCondition(True, "row_group.border.left.width")
        ucrChkRowGroupLeftWidth.AddParameterPresentCondition(False, "row_group.border.left.width", False)

        ucrChkRowGroupLeftColor.SetText("Left Color")
        ucrInputRowGroupLeftColor.SetParameter(New RParameter("row_group.border.left.color"))
        ucrChkRowGroupLeftColor.AddParameterPresentCondition(True, "row_group.border.left.color")
        ucrChkRowGroupLeftColor.AddParameterPresentCondition(False, "row_group.border.left.color", False)

        ucrChkRowBackColor.AddToLinkedControls(ucrRowBackColors, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowTextTransform.AddToLinkedControls(ucrInputRowTextTransform, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowGroupHorizontalPadding.AddToLinkedControls(ucrNudRowGroupHorizontalPadding, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkRowGroupPadding.AddToLinkedControls(ucrNudRowGroupPadding, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkRowFontSize.AddToLinkedControls(ucrNudRowFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkRowFontWeight.AddToLinkedControls(ucrInputRowFontWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowGroupTopColor.AddToLinkedControls(ucrInputRowGroupTopColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowGroupTopStyle.AddToLinkedControls(ucrInputRowGroupTopStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowGroupTopWidth.AddToLinkedControls(ucrNudRowGroupTopWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkRowGroupRightColor.AddToLinkedControls(ucrInputRowGroupRightColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowGroupRightStyle.AddToLinkedControls(ucrInputRowGroupRightStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowGroupRightWidth.AddToLinkedControls(ucrNudRowGroupRightWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkRowGroupBottomColor.AddToLinkedControls(ucrInputRowGroupBottomColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowGroupBottomStyle.AddToLinkedControls(ucrInputRowGroupBottomStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowGroupBottomWidth.AddToLinkedControls(ucrNudRowGroupBottomWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkRowGroupLeftColor.AddToLinkedControls(ucrInputRowGroupLeftColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowGroupLeftStyle.AddToLinkedControls(ucrInputRowGroupLeftStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkRowGroupLeftWidth.AddToLinkedControls(ucrNudRowGroupLeftWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        'Stub
        ucrChkStubBackColor.SetText("Background Color")
        ucrInputStubBackColor.SetParameter(New RParameter("stub.background.color"))
        ucrChkStubBackColor.AddParameterPresentCondition(True, "stub.background.color")
        ucrChkStubBackColor.AddParameterPresentCondition(False, "stub.background.color", False)

        ucrChkStubIndentLength.SetText("Indent Length")
        ucrNudStubIndentLength.SetParameter(New RParameter("stub.indent_length"))
        ucrNudStubIndentLength.SetRDefault(0)
        ucrChkStubIndentLength.AddParameterPresentCondition(True, "stub.indent_length")
        ucrChkStubIndentLength.AddParameterPresentCondition(False, "stub.indent_length", False)

        ucrChkStubTextTransform.SetText("Text Transform")
        ucrInputStubTextTransform.SetParameter(New RParameter("stub.text_transform"))
        ucrInputStubTextTransform.SetItems(dctTextTransform)
        ucrChkStubTextTransform.AddParameterPresentCondition(True, "stub.text_transform")
        ucrChkStubTextTransform.AddParameterPresentCondition(False, "stub.text_transform", False)

        ucrChkStubFontSize.SetText("Font Size")
        ucrNudStubFontSize.SetParameter(New RParameter("stub.font.size"))
        ucrNudStubFontSize.SetRDefault(0)
        ucrChkStubFontSize.AddParameterPresentCondition(True, "stub.font.size")
        ucrChkStubFontSize.AddParameterPresentCondition(False, "stub.font.size", False)

        ucrChkStubFontWeight.SetText("Font Weight")
        ucrInputStubFontWeight.SetParameter(New RParameter("stub.font.weight"))
        ucrInputStubFontWeight.SetItems(dctWeights)
        ucrChkStubFontWeight.AddParameterPresentCondition(True, "stub.font.weight")
        ucrChkStubFontWeight.AddParameterPresentCondition(False, "stub.font.weight", False)

        ucrChkStubBorderStyle.SetText("Style")
        ucrInputStubBorderStyle.SetParameter(New RParameter("stub.border.style"))
        ucrInputStubBorderStyle.SetItems(dctBorderStyles)
        ucrChkStubBorderStyle.AddParameterPresentCondition(True, "stub.border.style")
        ucrChkStubBorderStyle.AddParameterPresentCondition(False, "stub.border.style", False)

        ucrChkStubBorderWidth.SetText("Width")
        ucrNudStubBorderWidth.SetParameter(New RParameter("stub.border.width"))
        ucrNudStubBorderWidth.SetRDefault(0)
        ucrChkStubBorderWidth.AddParameterPresentCondition(True, "stub.border.width")
        ucrChkStubBorderWidth.AddParameterPresentCondition(False, "stub.border.width", False)

        ucrChkStubBorderColor.SetText("Color")
        ucrInputStubBorderColor.SetParameter(New RParameter("stub.border.color"))
        ucrChkStubBorderColor.AddParameterPresentCondition(True, "stub.border.color")
        ucrChkStubBorderColor.AddParameterPresentCondition(False, "stub.border.color", False)

        ucrChkStubGroupFontSize.SetText("Font Size")
        ucrNudStubGroupFontSize.SetParameter(New RParameter("stub_row_group.font.size"))
        ucrNudStubGroupFontSize.SetRDefault(0)
        ucrChkStubGroupFontSize.AddParameterPresentCondition(True, "stub_row_group.font.size")
        ucrChkStubGroupFontSize.AddParameterPresentCondition(False, "stub_row_group.font.size", False)

        ucrChkStubGroupFontWeight.SetText("Font Weight")
        ucrInputStubGroupFontWeight.SetParameter(New RParameter("stub_row_group.font.weight"))
        ucrInputStubGroupFontWeight.SetItems(dctWeights)
        ucrChkStubGroupFontWeight.AddParameterPresentCondition(True, "stub_row_group.font.weight")
        ucrChkStubGroupFontWeight.AddParameterPresentCondition(False, "stub_row_group.font.weight", False)

        ucrChkStubGroupTextTransform.SetText("Text Transform")
        ucrInputStubGroupTextTransform.SetParameter(New RParameter("stub_row_group.text_transform"))
        ucrInputStubGroupTextTransform.SetItems(dctTextTransform)
        ucrChkStubGroupTextTransform.AddParameterPresentCondition(True, "stub_row_group.text_transform")
        ucrChkStubGroupTextTransform.AddParameterPresentCondition(False, "stub_row_group.text_transform", False)

        ucrChkStubGroupBorderStyle.SetText("Style")
        ucrInputStubGroupBorderStyle.SetParameter(New RParameter("stub_row_group.border.style"))
        ucrInputStubGroupBorderStyle.SetItems(dctBorderStyles)
        ucrChkStubGroupBorderStyle.AddParameterPresentCondition(True, "stub_row_group.border.style")
        ucrChkStubGroupBorderStyle.AddParameterPresentCondition(False, "stub_row_group.border.style", False)

        ucrChkStubGroupBorderWidth.SetText("Width")
        ucrNudStubGroupBorderWidth.SetParameter(New RParameter("stub_row_group.border.width"))
        ucrNudStubGroupBorderWidth.SetRDefault(0)
        ucrChkStubGroupBorderWidth.AddParameterPresentCondition(True, "stub_row_group.border.width")
        ucrChkStubGroupBorderWidth.AddParameterPresentCondition(False, "stub_row_group.border.width", False)

        ucrChkStubGroupBorderColor.SetText("Color")
        ucrInputStubGroupBorderColor.SetParameter(New RParameter("stub_row_group.border.color"))
        ucrChkStubGroupBorderColor.AddParameterPresentCondition(True, "stub_row_group.border.color")
        ucrChkStubGroupBorderColor.AddParameterPresentCondition(False, "stub_row_group.border.color", False)

        ucrChkStubBackColor.AddToLinkedControls(ucrInputStubBackColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkStubTextTransform.AddToLinkedControls(ucrInputStubTextTransform, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkStubIndentLength.AddToLinkedControls(ucrNudStubIndentLength, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkStubFontSize.AddToLinkedControls(ucrNudStubFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkStubFontWeight.AddToLinkedControls(ucrInputStubFontWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkStubBorderColor.AddToLinkedControls(ucrInputStubBorderColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkStubBorderStyle.AddToLinkedControls(ucrInputStubBorderStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkStubBorderWidth.AddToLinkedControls(ucrNudStubBorderWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkStubGroupTextTransform.AddToLinkedControls(ucrInputStubGroupTextTransform, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkStubGroupFontSize.AddToLinkedControls(ucrNudStubGroupFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkStubGroupFontWeight.AddToLinkedControls(ucrInputStubGroupFontWeight, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkStubGroupBorderColor.AddToLinkedControls(ucrInputStubGroupBorderColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkStubGroupBorderStyle.AddToLinkedControls(ucrInputStubGroupBorderStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkStubGroupBorderWidth.AddToLinkedControls(ucrNudStubGroupBorderWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)

        'Footnotes
        ucrChkFootnotesBackColor.SetText("Background Color")
        ucrInputFootnotesBackColor.SetParameter(New RParameter("footnotes.background.color"))
        ucrChkFootnotesBackColor.AddParameterPresentCondition(True, "footnotes.background.color")
        ucrChkFootnotesBackColor.AddParameterPresentCondition(False, "footnotes.background.color", False)

        ucrChkFootnotesPadding.SetText("Vertical Padding")
        ucrNudFootnotesPadding.SetParameter(New RParameter("footnotes.padding"))
        ucrNudFootnotesPadding.SetRDefault(0)
        ucrChkFootnotesPadding.AddParameterPresentCondition(True, "footnotes.padding")
        ucrChkFootnotesPadding.AddParameterPresentCondition(False, "footnotes.padding", False)

        ucrChkFootnotesHorizontalPadding.SetText("Horizontal Padding")
        ucrNudFootnotesHorizontalPadding.SetParameter(New RParameter("footnotes.padding.horizontal"))
        ucrNudFootnotesHorizontalPadding.SetRDefault(0)
        ucrChkFootnotesHorizontalPadding.AddParameterPresentCondition(True, "footnotes.padding.horizontal")
        ucrChkFootnotesHorizontalPadding.AddParameterPresentCondition(False, "footnotes.padding.horizontal", False)

        ucrChkFootnotesFontSize.SetText("Font Size")
        ucrNudFootnotesFontSize.SetParameter(New RParameter("footnotes.font.size"))
        ucrNudFootnotesFontSize.SetRDefault(0)
        ucrChkFootnotesFontSize.AddParameterPresentCondition(True, "footnotes.font.size")
        ucrChkFootnotesFontSize.AddParameterPresentCondition(False, "footnotes.font.size", False)

        ucrChkFootnotesMarks.SetText("Footnotes Marks")
        ucrInputFootnotesMarks.SetParameter(New RParameter("footnotes.marks"))
        ucrInputFootnotesMarks.SetItems(dctFootnotesMarks)
        ucrChkFootnotesMarks.AddParameterPresentCondition(True, "footnotes.marks")
        ucrChkFootnotesMarks.AddParameterPresentCondition(False, "footnotes.marks", False)

        ucrChkFootnotesMultiline.SetText("Footnotes Multiline")
        ucrInputFootnotesMultiline.SetParameter(New RParameter("footnotes.multiline"))
        ucrInputFootnotesMultiline.SetItems(dctFootnotesMultiline)
        ucrChkFootnotesMultiline.AddParameterPresentCondition(True, "footnotes.multiline")
        ucrChkFootnotesMultiline.AddParameterPresentCondition(False, "footnotes.multiline", False)

        ucrChkFootnotesSeparator.SetText("Footnotes Separator")
        ucrInputFootnotesSeparator.SetParameter(New RParameter("footnotes.sep"))
        ucrInputFootnotesSeparator.SetItems(dctSeparators)
        ucrChkFootnotesSeparator.AddParameterPresentCondition(True, "footnotes.sep")
        ucrChkFootnotesSeparator.AddParameterPresentCondition(False, "footnotes.sep", False)

        ucrChkFootnotesBottomWidth.SetText("Bottom Width")
        ucrNudFootnotesBottomWidth.SetParameter(New RParameter("footnotes.border.bottom.width"))
        ucrNudFootnotesBottomWidth.SetRDefault(0)
        ucrChkFootnotesBottomWidth.AddParameterPresentCondition(True, "footnotes.border.bottom.width")
        ucrChkFootnotesBottomWidth.AddParameterPresentCondition(False, "footnotes.border.bottom.width", False)

        ucrChkFootnotesBottomStyles.SetText("Bottom Style")
        ucrInputFootnotesBottomStyle.SetParameter(New RParameter("footnotes.border.bottom.style"))
        ucrInputFootnotesBottomStyle.SetItems(dctBorderStyles)
        ucrChkFootnotesBottomStyles.AddParameterPresentCondition(True, "footnotes.border.bottom.style")
        ucrChkFootnotesBottomStyles.AddParameterPresentCondition(False, "footnotes.border.bottom.style", False)

        ucrChkFootnotesBottomColor.SetText("Bottom Color")
        ucrInputFootnotesBottomColor.SetParameter(New RParameter("footnotes.border.bottom.color"))
        ucrChkFootnotesBottomColor.AddParameterPresentCondition(True, "footnotes.border.bottom.color")
        ucrChkFootnotesBottomColor.AddParameterPresentCondition(False, "footnotes.border.bottom.color", False)

        ucrChkFootnotesSideWidth.SetText("Side Width")
        ucrNudFootnotesSideWidth.SetParameter(New RParameter("footnotes.border.lr.width"))
        ucrNudFootnotesSideWidth.SetRDefault(0)
        ucrChkFootnotesSideWidth.AddParameterPresentCondition(True, "footnotes.border.lr.width")
        ucrChkFootnotesSideWidth.AddParameterPresentCondition(False, "footnotes.border.lr.width", False)

        ucrChkFootnotesSideStyle.SetText("Side Style")
        ucrInputFootnotesSideStyle.SetParameter(New RParameter("footnotes.border.lr.style"))
        ucrInputFootnotesSideStyle.SetItems(dctBorderStyles)
        ucrChkFootnotesSideStyle.AddParameterPresentCondition(True, "footnotes.border.lr.style")
        ucrChkFootnotesSideStyle.AddParameterPresentCondition(False, "footnotes.border.lr.style", False)

        ucrChkFootnotesSideColor.SetText("Side Color")
        ucrInputFootnotesSideColor.SetParameter(New RParameter("footnotes.border.lr.colour"))
        ucrChkFootnotesSideColor.AddParameterPresentCondition(True, "footnotes.border.lr.colour")
        ucrChkFootnotesSideColor.AddParameterPresentCondition(False, "footnotes.border.lr.colour", False)

        ucrChkFootnotesBackColor.AddToLinkedControls(ucrInputFootnotesBackColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkFootnotesMarks.AddToLinkedControls(ucrInputFootnotesMarks, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkFootnotesFontSize.AddToLinkedControls(ucrNudFootnotesFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkFootnotesMultiline.AddToLinkedControls(ucrInputFootnotesMultiline, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkFootnotesSeparator.AddToLinkedControls(ucrInputFootnotesSeparator, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkFootnotesPadding.AddToLinkedControls(ucrNudFootnotesPadding, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkFootnotesHorizontalPadding.AddToLinkedControls(ucrNudFootnotesHorizontalPadding, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkFootnotesBottomWidth.AddToLinkedControls(ucrNudFootnotesBottomWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkFootnotesBottomStyles.AddToLinkedControls(ucrInputFootnotesBottomStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkFootnotesBottomColor.AddToLinkedControls(ucrInputFootnotesBottomColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkFootnotesSideWidth.AddToLinkedControls(ucrNudFootnotesSideWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkFootnotesSideStyle.AddToLinkedControls(ucrInputFootnotesSideStyle, {True}, bNewLinkedHideIfParameterMissing:=True, bNewLinkedAddRemoveParameter:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkFootnotesSideColor.AddToLinkedControls(ucrInputFootnotesSideColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")

        'Sourcenotes
        ucrChkSourcenotesBackColor.SetText("Background Color")
        ucrInputSourcenotesBackColor.SetParameter(New RParameter("source_notes.background.color"))
        ucrChkSourcenotesBackColor.AddParameterPresentCondition(True, "source_notes.background.color")
        ucrChkSourcenotesBackColor.AddParameterPresentCondition(False, "source_notes.background.color", False)

        ucrChkSourcenotesPadding.SetText("Vertical Padding")
        ucrNudSourcenotesPadding.SetParameter(New RParameter("source_notes.padding"))
        ucrNudSourcenotesPadding.SetRDefault(0)
        ucrChkSourcenotesPadding.AddParameterPresentCondition(True, "source_notes.padding")
        ucrChkSourcenotesPadding.AddParameterPresentCondition(False, "source_notes.padding", False)

        ucrChkSourcenotesHorizontalPadding.SetText("Horizontal Padding")
        ucrNudSourcenotesHorizontalPadding.SetParameter(New RParameter("source_notes.padding.horizontal"))
        ucrNudSourcenotesHorizontalPadding.SetRDefault(0)
        ucrChkSourcenotesHorizontalPadding.AddParameterPresentCondition(True, "source_notes.padding.horizontal")
        ucrChkSourcenotesHorizontalPadding.AddParameterPresentCondition(False, "source_notes.padding.horizontal", False)

        ucrChkSourcenotesFontSize.SetText("Font Size")
        ucrNudSourcenotesFontSize.SetParameter(New RParameter("source_notes.font.size"))
        ucrNudSourcenotesFontSize.SetRDefault(0)
        ucrChkSourcenotesFontSize.AddParameterPresentCondition(True, "source_notes.font.size")
        ucrChkSourcenotesFontSize.AddParameterPresentCondition(False, "source_notes.font.size", False)

        ucrChkSourcenotesMultiline.SetText("Sourcenotes Multiline")
        ucrInputSourcenotesMultiline.SetParameter(New RParameter("source_notes.multiline"))
        ucrInputSourcenotesMultiline.SetItems(dctFootnotesMultiline)
        ucrChkSourcenotesMultiline.AddParameterPresentCondition(True, "source_notes.multiline")
        ucrChkSourcenotesMultiline.AddParameterPresentCondition(False, "source_notes.multiline", False)

        ucrChkSourcenotesSeparator.SetText("Sourcenotes Separator")
        ucrInputSourcenotesSeparator.SetParameter(New RParameter("source_notes.sep"))
        ucrInputFootnotesSeparator.SetItems(dctSeparators)
        ucrChkSourcenotesSeparator.AddParameterPresentCondition(True, "source_notes.sep")
        ucrChkSourcenotesSeparator.AddParameterPresentCondition(False, "source_notes.sep", False)

        ucrChkSourcenotesBottomWidth.SetText("Bottom Width")
        ucrNudSourcenotesBottomWidth.SetParameter(New RParameter("source_notes.border.bottom.width"))
        ucrNudSourcenotesBottomWidth.SetRDefault(0)
        ucrChkSourcenotesBottomWidth.AddParameterPresentCondition(True, "source_notes.border.bottom.width")
        ucrChkSourcenotesBottomWidth.AddParameterPresentCondition(False, "source_notes.border.bottom.width", False)

        ucrChkSourcenotesBottomStyle.SetText("Bottom Style")
        ucrInputSourcenotesBottomStyle.SetParameter(New RParameter("source_notes.border.bottom.style"))
        ucrInputSourcenotesBottomStyle.SetItems(dctBorderStyles)
        ucrChkSourcenotesBottomStyle.AddParameterPresentCondition(True, "source_notes.border.bottom.style")
        ucrChkSourcenotesBottomStyle.AddParameterPresentCondition(False, "source_notes.border.bottom.style", False)

        ucrChkSourcenotesBottomColor.SetText("Bottom Color")
        ucrInputSourcenotesBottomColor.SetParameter(New RParameter("source_notes.border.bottom.color"))
        ucrChkSourcenotesBottomColor.AddParameterPresentCondition(True, "source_notes.border.bottom.color")
        ucrChkSourcenotesBottomColor.AddParameterPresentCondition(False, "source_notes.border.bottom.color", False)

        ucrChkSourcenotesSideWidth.SetText("Side Width")
        ucrNudSourcenotesSideWidth.SetParameter(New RParameter("source_notes.border.lr.width"))
        ucrNudSourcenotesSideWidth.SetRDefault(0)
        ucrChkSourcenotesSideWidth.AddParameterPresentCondition(True, "source_notes.border.lr.width")
        ucrChkSourcenotesSideWidth.AddParameterPresentCondition(False, "source_notes.border.lr.width", False)

        ucrChkSourcenotesSideStyle.SetText("Side Style")
        ucrInputSourcenotesSideStyle.SetParameter(New RParameter("source_notes.border.lr.style"))
        ucrInputSourcenotesSideStyle.SetItems(dctBorderStyles)
        ucrChkSourcenotesSideStyle.AddParameterPresentCondition(True, "source_notes.border.lr.style")
        ucrChkSourcenotesSideStyle.AddParameterPresentCondition(False, "source_notes.border.lr.style", False)

        ucrChkSourcenotesSideColor.SetText("Side Color")
        ucrInputSourcenotesSideColor.SetParameter(New RParameter("source_notes.border.lr.colour"))
        ucrChkSourcenotesSideColor.AddParameterPresentCondition(True, "source_notes.border.lr.colour")
        ucrChkSourcenotesSideColor.AddParameterPresentCondition(False, "source_notes.border.lr.colour", False)

        ucrChkSourcenotesBackColor.AddToLinkedControls(ucrInputSourcenotesBackColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkSourcenotesFontSize.AddToLinkedControls(ucrNudSourcenotesFontSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkSourcenotesMultiline.AddToLinkedControls(ucrInputSourcenotesMultiline, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkSourcenotesSeparator.AddToLinkedControls(ucrInputSourcenotesSeparator, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkSourcenotesPadding.AddToLinkedControls(ucrNudSourcenotesPadding, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkSourcenotesHorizontalPadding.AddToLinkedControls(ucrNudSourcenotesHorizontalPadding, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkSourcenotesBottomWidth.AddToLinkedControls(ucrNudSourcenotesBottomWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkSourcenotesBottomStyle.AddToLinkedControls(ucrInputSourcenotesBottomStyle, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkSourcenotesBottomColor.AddToLinkedControls(ucrInputSourcenotesBottomColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkSourcenotesSideWidth.AddToLinkedControls(ucrNudSourcenotesSideWidth, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=0)
        ucrChkSourcenotesSideStyle.AddToLinkedControls(ucrInputSourcenotesSideStyle, {True}, bNewLinkedHideIfParameterMissing:=True, bNewLinkedAddRemoveParameter:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")
        ucrChkSourcenotesSideColor.AddToLinkedControls(ucrInputSourcenotesSideColor, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultState:="NULL")

    End Sub

    Public Sub SetRCode(bReset As Boolean, clsNewThemesTabOption As RFunction)
        bRCodeSet = False
        clsThemesTabOptionsFunction = clsNewThemesTabOption

        If Not bControlsInitialised Then
            InitialiseControls()
        End If

        'Titles
        ucrChkBackgroundColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputBackgroundColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkAlignment.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputAlignment.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSubTitleSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudSubTitleSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSubTitleWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSubTitleWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkBoxLength.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudBoxLength.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkBoxWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudBoxWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkBottomColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputBottomColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSideColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSideColour.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)

        'Tables
        ucrChkTableAlign.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableAlign.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrTableBackgroundColors.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableFontColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableFontColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableLayout.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableLayout.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableFontNames.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableFontNames.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableFontStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableFontStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableTopColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableTopColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableTopStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableTopStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableTopWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableTopWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableRightColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableRightColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableRightStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableRightStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableRightWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableRightWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableLeftColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableLeftColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableLeftStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputTableLeftStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkTableLeftWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudTableLeftWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)

        'Columns
        ucrChkColumnsBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsHorizontalPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsHorizontalPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsTextTransform.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsTextTransform.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColomnsTopColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsTopColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsTopStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsTopStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsTopWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsTopWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsVlineColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsVlineColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsVlineStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsVlineStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsVlineWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsVlineWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsSideColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsSideColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputColumnsSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkColumnsSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudColumnsSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)

        'Rows
        ucrChkRowBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrRowBackColors.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudRowGroupPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupHorizontalPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudRowGroupHorizontalPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowTextTransform.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputRowTextTransform.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputRowFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudRowFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupTopColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputRowGroupTopColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupTopStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputRowGroupTopStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupTopWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudRowGroupTopWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupRightColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputRowGroupRightColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupRightStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputRowGroupRightStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupRightWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudRowGroupRightWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputRowGroupBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputRowGroupBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudRowGroupBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupLeftColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputRowGroupLeftColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupLeftStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputRowGroupLeftStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkRowGroupLeftWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudRowGroupLeftWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)

        'Stub
        ucrChkStubBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputStubBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubIndentLength.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudStubIndentLength.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubTextTransform.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputStubTextTransform.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputStubFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudStubFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubBorderColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputStubBorderColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubBorderStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputStubBorderStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubBorderWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudStubBorderWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubGroupTextTransform.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputStubGroupTextTransform.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubGroupFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputStubGroupFontWeight.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubGroupFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudStubGroupFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubGroupBorderColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputStubGroupBorderColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubGroupBorderStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputStubGroupBorderStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkStubGroupBorderWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudStubGroupBorderWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)

        'Footnotes
        ucrChkFootnotesBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudFootnotesPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesHorizontalPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudFootnotesHorizontalPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesMarks.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputFootnotesMarks.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesMultiline.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputFootnotesMultiline.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesSeparator.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputFootnotesSeparator.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudFootnotesFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudFootnotesBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesBottomStyles.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputFootnotesBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputFootnotesBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudFootnotesSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputFootnotesSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkFootnotesSideColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputFootnotesSideColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)

        'Sourcenotes
        ucrChkSourcenotesBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesBackColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudSourcenotesPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesHorizontalPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudSourcenotesHorizontalPadding.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesMultiline.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSourcenotesMultiline.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesSeparator.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSourcenotesSeparator.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudSourcenotesFontSize.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudSourcenotesBottomWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSourcenotesBottomStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSourcenotesBottomColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrNudSourcenotesSideWidth.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSourcenotesSideStyle.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrChkSourcenotesSideColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        ucrInputSourcenotesSideColor.SetRCode(clsThemesTabOptionsFunction, bReset, bCloneIfNeeded:=True)
        bRCodeSet = True
    End Sub

    Private Sub tbpSummaryThemes_Selecting(sender As Object, e As TabControlCancelEventArgs) Handles tbpSummaryThemes.Selecting
        If e.TabPageIndex = 2 Or e.TabPageIndex = 3 Or e.TabPageIndex = 4 Then
            e.Cancel = True
        End If
    End Sub
End Class