'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class ucrDistributions
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("instat.ucrDistributions", GetType(ucrDistributions).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Public Shared ReadOnly Property lblDistributionType_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lblDistributionType.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=-1,Y=5}.
        '''</summary>
        Public Shared ReadOnly Property lblDistributionType_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("lblDistributionType.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=62, Height=13}.
        '''</summary>
        Public Shared ReadOnly Property lblDistributionType_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("lblDistributionType.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 0.
        '''</summary>
        Public Shared ReadOnly Property lblDistributionType_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("lblDistributionType.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distribution:.
        '''</summary>
        Public Shared ReadOnly Property lblDistributionType_Text() As String
            Get
                Return ResourceManager.GetString("lblDistributionType.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=67,Y=3}.
        '''</summary>
        Public Shared ReadOnly Property ucrInputDistributions_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrInputDistributions.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=137, Height=21}.
        '''</summary>
        Public Shared ReadOnly Property ucrInputDistributions_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrInputDistributions.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Public Shared ReadOnly Property ucrInputDistributions_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ucrInputDistributions.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
    End Class
End Namespace
