#Labels for strings which will be added to logs
Set_property="Set"
Added_col="Added column"
Replaced_col="Replaced column"
Renamed_col="Renamed column"
Removed_col="Removed column"
Added_metadata="Added metadata"
Added_variables_metadata="Added variables metadata"
Added_filter="Added filter"
Converted_col_="Converted column"
Replaced_value="Replaced value"
Removed_row="Removed row"
Inserted_col = "Inserted column"
Move_col = "Moved column"
Col_order = "Order of columns"
Inserted_row = "Inserted row"
Copy_cols = "Copied columns"
Merged_data = "Merged data"

#meta data labels
data_name_label="data_name"
is_calculated_label="Is_Calculated"
decimal_places_label="Decimal_Places"
columns_label="columns"
summarised_from_label="summarised_from"
key_label="key"
row_count_label="Row_Count"
column_count_label="Column_Count"

#variables_metadata labels
display_decimal_label="Display_Decimal"
name_label="Name"
is_factor_label="Is_Factor"
data_type_label="Data_Type"
is_hidden_label="Is_Hidden"
is_protected_label="Is_Protected"