# Necessary packages for the Instat Object
packs <- c("openxlsx", "reshape2", "lubridate","plyr", "rtf", "ggplot2", "extRemes", "GGally", "CCA", "plotrix", "agridat", "DAAG", "FactoMineR", "plotrix", "agridat", "candisc", "R6", "openair", "circular", "survival", "Evapotranspiration", "clifro", "devtools", "factoextra", "circlize", "CircStats", "proto", "tidyr", "gridExtra", "tidyr", "ggfortify", "rio", "readxl", "lme4", "dummies", "ggthemes", "lazyeval", "stringr", "httr", "jsonlite", "fitdistrplus", "visreg")
# Packages including dependencies (generated from miniCRAN package)
packs <- c("abind", "agridat", "assertthat", "BH", "bitops", "boot", "candisc", "car", "CCA", "cellranger", "chron", "circlize", "CircStats", "circular", "class", "clifro", "cluster", "colorspace", "csvy", "curl", "DAAG", "data.table", "DBI", "dendextend", "DEoptimR", "devtools", "dichromat", "digest", "diptest", "distillery", "dplyr", "dummies", "ellipse", "evaluate", "Evapotranspiration", "extRemes", "factoextra", "FactoMineR", "fda", "fields", "fitdistrplus", "flashClust", "flexmix", "foreign", "formatR", "fpc", "GGally", "ggfortify", "ggplot2", "ggrepel", "ggthemes", "git2r", "GlobalOptions", "gridExtra", "gtable", "haven", "heplots", "hexbin", "highr", "hms", "httr", "jsonlite", "kernlab", "knitr", "labeling", "lattice", "latticeExtra", "lazyeval", "leaps", "lme4", "Lmoments", "lubridate", "magrittr", "mapdata", "mapproj", "maps", "markdown", "MASS", "Matrix", "MatrixModels", "mclust", "memoise", "mgcv", "mime", "minqa", "modeltools", "munsell", "mvtnorm", "nlme", "nloptr", "nnet", "openair", "openssl", "openxlsx", "pbkrtest", "plotrix", "plyr", "png", "prabclus", "proto", "quantreg", "R.methodsS3", "R.oo", "R6", "RColorBrewer", "Rcpp", "RcppEigen", "RCurl", "readODS", "readr", "readxl", "rematch", "reshape", "reshape2", "RgoogleMaps", "rio", "robustbase", "rstudioapi", "rtf", "scales", "scatterplot3d", "selectr", "shape", "spam", "SparseM", "stringi", "stringr", "survival", "tibble", "tidyr", "triebeard", "trimcluster", "urltools", "visreg", "whisker", "withr", "XML", "xml2", "yaml", "zoo")
success <- invisible(sapply(packs, function(x) length(find.package(x, quiet = TRUE))>0))
if(!all(success)) install.packages(names(success)[!success], repos = paste0("file:///", getwd(), "/extras"), type = "win.binary")
#success <- suppressWarnings(sapply(packs, require, character.only = TRUE))
#if(!all(success)) install.packages(names(success)[!success], repos = paste0("file:///", getwd(), "/RPackages"), type = "win.binary")
#require will ensure packages load correctly, but not sensible to load all
#sapply(names(success)[!success], require, character.only = TRUE)
#Needed when ggfortify was not on CRAN
#if(!suppressWarnings(require(ggfortify))) install.packages(paste0(getwd(), "/RPackages", "/ggfortify_0.1.0.tar.gz"), repos = NULL, type="source")
library(plyr)
library(dplyr)
library(openxlsx)
library(reshape2)
library(lubridate)
library(rtf)
library(ggplot2)
library(extRemes)
library(DAAG)
library(ggfortify)
library(mosaic)
library(GGally)
library(FactoMineR)
library(plotrix)
library(agridat)
library(candisc)
library(R6)
library(openair)
library(circular)
library(survival)
library(Evapotranspiration)
library(clifro)
library(devtools)
library(factoextra)
library(circlize)
library(CircStats)
library(rio)
library(readxl)
library(lme4)
library(dummies)
library(ggthemes)
library(lazyeval)
library(stringr)
library(httr)
library(jsonlite)
library(fitdistrplus)
library(visreg)
setwd(dirname(parent.frame(2)$ofile))


source("instat_object_R6.R")
source("data_object_R6.R")
source("labels_and_defaults.R")
source("stand_alone_functions.R")
files <- sort(dir(file.path(getwd(), 'Backend_Components/'),pattern=".R$", full.names = TRUE))
lapply(files, source, chdir = TRUE)