#!/usr/bin/env python3
"""
generate_r_scripts.py

Generates install_packages_generated.R and check_packages_generated.R from r_packages.json.
The JSON is the single source of truth.  Edit it there, then re-run this
script to regenerate both R files.

Usage
-----
    python generate_r_scripts.py [json_path] [install_out] [check_out]

    json_path    Path to r_packages.json  (default: r_packages.json in same dir)
    install_out  Output path for install script
                 (default: install_packages_generated.R in same dir)
    check_out    Output path for check script
                 (default: check_packages_generated.R in same dir)

Package types
-------------
    source      Archived CRAN tarball; installed via
                    install.packages(url, repos=NULL, type="source")
    win.binary  Binary CRAN package; installed via
                    install.packages(name, repos=repo, type="win.binary")
                Packages sharing the same priority + repo are batched into a
                single install.packages(c(...)) call.
    github      GitHub package; installed via
                    devtools::install_github(repo, ...)
                The .libPaths() internal-library block is inserted automatically
                before the first github-type package.

Package options (optional JSON fields)
--------------------------------------
    force               bool  — adds force = TRUE to devtools::install_github()
    install_dependencies  bool  — sets the dependencies argument.
                          Defaults to FALSE if not present in the JSON entry.
"""

import json
import sys
from itertools import groupby
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
R_DIR = SCRIPT_DIR.parent / "instat" / "static" / "InstatObject" / "R"

# ---------------------------------------------------------------------------
# The .libPaths() block that must run before any GitHub installs
# ---------------------------------------------------------------------------
_INTERNAL_LIBRARY_BLOCK = """\
# Only use internal library
if (length(.libPaths()) >= 2) {
  current_paths <- .libPaths()
  .libPaths(current_paths[c(1, 3)[c(1, 3) <= length(current_paths)]])
}"""

# Section header comments, keyed by package type
_SECTION_LABELS = {
    "source":     "Install packages from CRAN archive",
    "win.binary": "Install packages from CRAN",
    "github":     "Install packages from GitHub",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _install_deps(pkg: dict) -> bool:
    """Returns the install_dependencies value; defaults to False if not set."""
    return bool(pkg.get("install_dependencies", False))


def _load(json_path: Path):
    with open(json_path, encoding="utf-8") as fh:
        data = json.load(fh)
    settings = data.get("settings", {})
    packages = sorted(
        data.get("packages", []),
        key=lambda p: (p.get("priority", 9999), p["type"], p.get("installed_from", ""), _install_deps(p), p.get("force", False), p["name"]),
    )
    return settings, packages


def _group_key(pkg):
    """Packages with the same (priority, type, installed_from, deps, force) are batched."""
    return (pkg.get("priority", 9999), pkg["type"], pkg.get("installed_from", ""), _install_deps(pkg), pkg.get("force", False))


def _github_line(pkg: dict) -> str:
    deps_r = "TRUE" if _install_deps(pkg) else "FALSE"
    parts = [f'devtools::install_github("{pkg["installed_from"]}"']
    parts.append(f"dependencies = {deps_r}")
    if pkg.get("force"):
        parts.append("force = TRUE")
    parts.append('upgrade = "never"')
    return ", ".join(parts) + ")"


# ---------------------------------------------------------------------------
# Generator: install_packages_generated.R (default)
# ---------------------------------------------------------------------------

def generate_install_r(settings: dict, packages: list, out_path: Path) -> None:
    tz = settings.get("timezone", "GMT")
    lc = settings.get("locale_time", "C")

    lines = [
        f"# {out_path.name}",
        "# Auto-generated by generate_r_scripts.py — do not edit directly.",
        "# Edit r_packages.json and re-run generate_r_scripts.py instead.",
        "",
        f"Sys.setenv(TZ='{tz}')",
        f'Sys.setlocale("LC_TIME", "{lc}")',
        "",
    ]

    internal_library_done = False
    last_type = None

    for (priority, pkg_type, source, deps, force), group_iter in groupby(packages, key=_group_key):
        group = list(group_iter)
        deps_r = "TRUE" if deps else "FALSE"

        # Insert internal-library block once, just before the first GitHub install
        if pkg_type == "github" and not internal_library_done:
            lines += ["", _INTERNAL_LIBRARY_BLOCK, ""]
            internal_library_done = True

        # Emit a section header when the install type changes
        if pkg_type != last_type:
            label = _SECTION_LABELS.get(pkg_type, pkg_type)
            lines.append(f"#{label}")
            last_type = pkg_type

        if pkg_type == "source":
            for pkg in group:
                lines.append(
                    f'install.packages("{pkg["installed_from"]}", '
                    f'repos = NULL, type = "source", dependencies = {deps_r})'
                )

        elif pkg_type == "win.binary":
            if len(group) == 1:
                pkg = group[0]
                lines.append(
                    f'install.packages("{pkg["name"]}", '
                    f"dependencies = {deps_r}, repos = '{source}', "
                    f'type = "win.binary")'
                )
            else:
                name_csv = ",\n    ".join(f'"{p["name"]}"' for p in group)
                lines += [
                    "install.packages(",
                    f"  c(",
                    f"    {name_csv}",
                    "  ),",
                    f"  dependencies = {deps_r}, repos = '{source}', type = \"win.binary\"",
                    ")",
                ]

        elif pkg_type == "github":
            for pkg in group:
                lines.append(_github_line(pkg))

        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Written: {out_path}")


# ---------------------------------------------------------------------------
# Generator: check_packages.R
# ---------------------------------------------------------------------------

def generate_check_r(packages: list, out_path: Path) -> None:
    # Deduplicate while preserving install order
    seen: set = set()
    unique: list = []
    for pkg in packages:
        if pkg["name"] not in seen:
            seen.add(pkg["name"])
            unique.append(pkg["name"])

    pkg_lines = ",\n".join(f'  "{n}"' for n in unique)

    lines = [
        f"# {out_path.name}",
        "# Auto-generated by generate_r_scripts.py — do not edit directly.",
        "# Edit r_packages.json and re-run generate_r_scripts.py instead.",
        "# Verifies that all required R packages are installed.",
        "#",
        "# Usage: Rscript check_packages.R [workspace_root] [output_file]",
        "#   workspace_root  Unused; kept for workflow compatibility",
        "#   output_file     Path to write the markdown report",
        "#                   (default: package-check-report.txt)",
        "",
        "args        <- commandArgs(trailingOnly = TRUE)",
        'output_file <- if (length(args) >= 2) args[2] else "package-check-report.txt"',
        "",
        "# --------------------------------------------------------------------------",
        "# Full list of required packages (mirrors r_packages.json)",
        "# --------------------------------------------------------------------------",
        "packages <- c(",
        pkg_lines,
        ")",
        "",
        "# --------------------------------------------------------------------------",
        "# Check against installed packages and report",
        "# --------------------------------------------------------------------------",
        "installed   <- rownames(installed.packages())",
        "missing     <- packages[!packages %in% installed]",
        "",
        "n_total     <- length(packages)",
        "n_missing   <- length(missing)",
        "n_installed <- n_total - n_missing",
        "",
        "if (n_missing == 0) {",
        '  status_icon <- "\\u2705"',
        '  status_line <- paste("All", n_total, "packages are installed.")',
        "} else {",
        '  status_icon <- "\\u274c"',
        '  status_line <- paste(n_missing, "of", n_total, "package(s) are not installed.")',
        "}",
        "",
        "report <- c(",
        '  "<!-- package-check-report:start -->",',
        '  paste("##", status_icon, "R Package Check"),',
        '  "",',
        '  paste0("**", status_line, "**"),',
        '  "",',
        '  "| Metric | Count |",',
        '  "|--------|-------|",',
        '  paste0("| Total packages checked | ", n_total, " |"),',
        '  paste0("| Installed              | ", n_installed, " |"),',
        '  paste0("| Missing                | ", n_missing, " |")',
        ")",
        "",
        "if (n_missing > 0) {",
        '  report <- c(report, "", "### Missing Packages", "")',
        '  report <- c(report, paste0("- `", missing, "`"))',
        "}",
        "",
        'report <- c(report, "", "<!-- package-check-report:end -->")',
        "",
        "writeLines(report, output_file)",
        'cat(paste(report, collapse = "\\n"), "\\n")',
        "",
        "if (n_missing > 0) quit(status = 1L)",
        "",
    ]

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Written: {out_path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    argv = sys.argv[1:]

    json_path    = Path(argv[0]) if len(argv) > 0 else R_DIR / "r_packages.json"
    install_out  = Path(argv[1]) if len(argv) > 1 else R_DIR / "install_packages_generated.R"
    check_out    = Path(argv[2]) if len(argv) > 2 else R_DIR / "check_packages_generated.R"

    if not json_path.exists():
        print(f"Error: {json_path} not found.", file=sys.stderr)
        sys.exit(1)

    print(f"Reading: {json_path}")
    settings, packages = _load(json_path)

    print("Generating:")
    generate_install_r(settings, packages, install_out)
    generate_check_r(packages, check_out)
    print("Done.")


if __name__ == "__main__":
    main()
