'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("instat.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend ReadOnly Property Add() As String
            Get
                Return ResourceManager.GetString("Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alecive_Flatwoken_Apps_Run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alecive-Flatwoken-Apps-Run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Analysis of Variance.
        '''</summary>
        Friend ReadOnly Property Analysis_of_Variance() As String
            Get
                Return ResourceManager.GetString("Analysis_of_Variance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available  Variables.
        '''</summary>
        Friend ReadOnly Property Available_Variables() As String
            Get
                Return ResourceManager.GetString("Available_Variables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Box Plot.
        '''</summary>
        Friend ReadOnly Property Box_Plot() As String
            Get
                Return ResourceManager.GetString("Box_Plot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Boxplot.
        '''</summary>
        Friend ReadOnly Property Boxplot() As String
            Get
                Return ResourceManager.GetString("Boxplot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculations.
        '''</summary>
        Friend ReadOnly Property Calculations() As String
            Get
                Return ResourceManager.GetString("Calculations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Carlosjj_Microsoft_Office_2013_Excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carlosjj-Microsoft-Office-2013-Excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check Duplicates.
        '''</summary>
        Friend ReadOnly Property Check_Duplicates() As String
            Get
                Return ResourceManager.GetString("Check_Duplicates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose Statistics.
        '''</summary>
        Friend ReadOnly Property Choose_Statistics() As String
            Get
                Return ResourceManager.GetString("Choose_Statistics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CircularStatisctics.
        '''</summary>
        Friend ReadOnly Property Circular_Statisctics() As String
            Get
                Return ResourceManager.GetString("Circular_Statisctics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear.
        '''</summary>
        Friend ReadOnly Property Clear() As String
            Get
                Return ResourceManager.GetString("Clear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear(Remove).
        '''</summary>
        Friend ReadOnly Property Clear_Remove() As String
            Get
                Return ResourceManager.GetString("Clear_Remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear Del.
        '''</summary>
        Friend ReadOnly Property Clear1() As String
            Get
                Return ResourceManager.GetString("Clear1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Climatic.
        '''</summary>
        Friend ReadOnly Property Climatic() As String
            Get
                Return ResourceManager.GetString("Climatic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property Close() As String
            Get
                Return ResourceManager.GetString("Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close Worksheet.
        '''</summary>
        Friend ReadOnly Property Close_Worksheet() As String
            Get
                Return ResourceManager.GetString("Close_Worksheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column Properties.
        '''</summary>
        Friend ReadOnly Property Column_Properties() As String
            Get
                Return ResourceManager.GetString("Column_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column Statistics.
        '''</summary>
        Friend ReadOnly Property Column_Statistics() As String
            Get
                Return ResourceManager.GetString("Column_Statistics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Command and Output Window.
        '''</summary>
        Friend ReadOnly Property Command_and_Output_Window() As String
            Get
                Return ResourceManager.GetString("Command_and_Output_Window", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Command Logging.
        '''</summary>
        Friend ReadOnly Property Command_Logging() As String
            Get
                Return ResourceManager.GetString("Command_Logging", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy.
        '''</summary>
        Friend ReadOnly Property Copy() As String
            Get
                Return ResourceManager.GetString("Copy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy Special.
        '''</summary>
        Friend ReadOnly Property Copy_Special() As String
            Get
                Return ResourceManager.GetString("Copy_Special", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy Special Ctrl+Y.
        '''</summary>
        Friend ReadOnly Property Copy_Special1() As String
            Get
                Return ResourceManager.GetString("Copy_Special1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cumulative Frequency.
        '''</summary>
        Friend ReadOnly Property Cumulative_Frequency() As String
            Get
                Return ResourceManager.GetString("Cumulative_Frequency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cut.
        '''</summary>
        Friend ReadOnly Property Cut() As String
            Get
                Return ResourceManager.GetString("Cut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data.
        '''</summary>
        Friend ReadOnly Property Data() As String
            Get
                Return ResourceManager.GetString("Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data View.
        '''</summary>
        Friend ReadOnly Property Data_View() As String
            Get
                Return ResourceManager.GetString("Data_View", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Describe.
        '''</summary>
        Friend ReadOnly Property Describe() As String
            Get
                Return ResourceManager.GetString("Describe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display.
        '''</summary>
        Friend ReadOnly Property Display() As String
            Get
                Return ResourceManager.GetString("Display", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diversity.
        '''</summary>
        Friend ReadOnly Property Diversity() As String
            Get
                Return ResourceManager.GetString("Diversity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dotplot.
        '''</summary>
        Friend ReadOnly Property Dotplot() As String
            Get
                Return ResourceManager.GetString("Dotplot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dry Spell.
        '''</summary>
        Friend ReadOnly Property Dry_Spell() As String
            Get
                Return ResourceManager.GetString("Dry_Spell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicate(copy columns).
        '''</summary>
        Friend ReadOnly Property Duplicate_copy_columns() As String
            Get
                Return ResourceManager.GetString("Duplicate_copy_columns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Earliest day.
        '''</summary>
        Friend ReadOnly Property Earliest_day() As String
            Get
                Return ResourceManager.GetString("Earliest_day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend ReadOnly Property Edit() As String
            Get
                Return ResourceManager.GetString("Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter.
        '''</summary>
        Friend ReadOnly Property Enter() As String
            Get
                Return ResourceManager.GetString("Enter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend ReadOnly Property Exit_() As String
            Get
                Return ResourceManager.GetString("Exit_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expand.
        '''</summary>
        Friend ReadOnly Property Expand() As String
            Get
                Return ResourceManager.GetString("Expand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export_as.
        '''</summary>
        Friend ReadOnly Property Export_as() As String
            Get
                Return ResourceManager.GetString("Export_as", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extremes.
        '''</summary>
        Friend ReadOnly Property Extremes() As String
            Get
                Return ResourceManager.GetString("Extremes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Factor Variable.
        '''</summary>
        Friend ReadOnly Property Factor_Variable() As String
            Get
                Return ResourceManager.GetString("Factor_Variable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File .
        '''</summary>
        Friend ReadOnly Property File() As String
            Get
                Return ResourceManager.GetString("File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find.
        '''</summary>
        Friend ReadOnly Property Find() As String
            Get
                Return ResourceManager.GetString("Find", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find Ctrl+F.
        '''</summary>
        Friend ReadOnly Property Find1() As String
            Get
                Return ResourceManager.GetString("Find1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flags.
        '''</summary>
        Friend ReadOnly Property Flags() As String
            Get
                Return ResourceManager.GetString("Flags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Font Ctrl+T.
        '''</summary>
        Friend ReadOnly Property Font() As String
            Get
                Return ResourceManager.GetString("Font", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Freequency Chart.
        '''</summary>
        Friend ReadOnly Property Freequency_Chart() As String
            Get
                Return ResourceManager.GetString("Freequency_Chart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to French.
        '''</summary>
        Friend ReadOnly Property French() As String
            Get
                Return ResourceManager.GetString("French", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Graphics.
        '''</summary>
        Friend ReadOnly Property Graphics() As String
            Get
                Return ResourceManager.GetString("Graphics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group.
        '''</summary>
        Friend ReadOnly Property Group() As String
            Get
                Return ResourceManager.GetString("Group", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Histogram.
        '''</summary>
        Friend ReadOnly Property Histogram() As String
            Get
                Return ResourceManager.GetString("Histogram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import ASCII.
        '''</summary>
        Friend ReadOnly Property Import_ASCII() As String
            Get
                Return ResourceManager.GetString("Import_ASCII", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import/Export.
        '''</summary>
        Friend ReadOnly Property Import_Export() As String
            Get
                Return ResourceManager.GetString("Import_Export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicator Variables.
        '''</summary>
        Friend ReadOnly Property Indicator_Variables() As String
            Get
                Return ResourceManager.GetString("Indicator_Variables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interractions.
        '''</summary>
        Friend ReadOnly Property Interractions() As String
            Get
                Return ResourceManager.GetString("Interractions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend ReadOnly Property Language() As String
            Get
                Return ResourceManager.GetString("Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Length of Dry Spell.
        '''</summary>
        Friend ReadOnly Property Length_of_Dry_Spell() As String
            Get
                Return ResourceManager.GetString("Length_of_Dry_Spell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Graph.
        '''</summary>
        Friend ReadOnly Property Load_Graph() As String
            Get
                Return ResourceManager.GetString("Load_Graph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manage.
        '''</summary>
        Friend ReadOnly Property Manage() As String
            Get
                Return ResourceManager.GetString("Manage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manipulate.
        '''</summary>
        Friend ReadOnly Property Manipulate() As String
            Get
                Return ResourceManager.GetString("Manipulate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Worksheet... CTRL+N.
        '''</summary>
        Friend ReadOnly Property New_Worksheet() As String
            Get
                Return ResourceManager.GetString("New_Worksheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non-Parametric.
        '''</summary>
        Friend ReadOnly Property Non_Parametric() As String
            Get
                Return ResourceManager.GetString("Non_Parametric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Yet Implemented.
        '''</summary>
        Friend ReadOnly Property Not_Yet_Implemented() As String
            Get
                Return ResourceManager.GetString("Not_Yet_Implemented", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of Rain Days.
        '''</summary>
        Friend ReadOnly Property Number_of_Rain_Days() As String
            Get
                Return ResourceManager.GetString("Number_of_Rain_Days", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ODBC Query.
        '''</summary>
        Friend ReadOnly Property ODBC_Query() As String
            Get
                Return ResourceManager.GetString("ODBC_Query", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ok.
        '''</summary>
        Friend ReadOnly Property Ok() As String
            Get
                Return ResourceManager.GetString("Ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend ReadOnly Property Open() As String
            Get
                Return ResourceManager.GetString("Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open From Library.
        '''</summary>
        Friend ReadOnly Property Open_From_Library() As String
            Get
                Return ResourceManager.GetString("Open_From_Library", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Worksheet.
        '''</summary>
        Friend ReadOnly Property Open_Worksheet() As String
            Get
                Return ResourceManager.GetString("Open_Worksheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend ReadOnly Property Options() As String
            Get
                Return ResourceManager.GetString("Options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output.
        '''</summary>
        Friend ReadOnly Property Output() As String
            Get
                Return ResourceManager.GetString("Output", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output Spooling.
        '''</summary>
        Friend ReadOnly Property Output_Spooling() As String
            Get
                Return ResourceManager.GetString("Output_Spooling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output Window.
        '''</summary>
        Friend ReadOnly Property Output_Window() As String
            Get
                Return ResourceManager.GetString("Output_Window", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_window_duplicate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Actions-window-duplicate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Status_dialog_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Status-dialog-error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paomedia_Small_N_Flat_Window_layout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paomedia-Small-N-Flat-Window-layout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paste.
        '''</summary>
        Friend ReadOnly Property Paste() As String
            Get
                Return ResourceManager.GetString("Paste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paste Ctrl+V.
        '''</summary>
        Friend ReadOnly Property Paste1() As String
            Get
                Return ResourceManager.GetString("Paste1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plot.
        '''</summary>
        Friend ReadOnly Property Plot() As String
            Get
                Return ResourceManager.GetString("Plot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Polynomials.
        '''</summary>
        Friend ReadOnly Property Polynomials() As String
            Get
                Return ResourceManager.GetString("Polynomials", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print.
        '''</summary>
        Friend ReadOnly Property Print() As String
            Get
                Return ResourceManager.GetString("Print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print Preview.
        '''</summary>
        Friend ReadOnly Property Print_Preview() As String
            Get
                Return ResourceManager.GetString("Print_Preview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Probability Distribution.
        '''</summary>
        Friend ReadOnly Property Probability_Distribution() As String
            Get
                Return ResourceManager.GetString("Probability_Distribution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Probability Plot.
        '''</summary>
        Friend ReadOnly Property Probability_Plot() As String
            Get
                Return ResourceManager.GetString("Probability_Plot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Random Samples.
        '''</summary>
        Friend ReadOnly Property Random_Samples() As String
            Get
                Return ResourceManager.GetString("Random_Samples", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recall.
        '''</summary>
        Friend ReadOnly Property Recall() As String
            Get
                Return ResourceManager.GetString("Recall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recode.
        '''</summary>
        Friend ReadOnly Property Recode() As String
            Get
                Return ResourceManager.GetString("Recode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Regression.
        '''</summary>
        Friend ReadOnly Property Regression() As String
            Get
                Return ResourceManager.GetString("Regression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Regular Sequence.
        '''</summary>
        Friend ReadOnly Property Regular_Sequence() As String
            Get
                Return ResourceManager.GetString("Regular_Sequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove.
        '''</summary>
        Friend ReadOnly Property Remove() As String
            Get
                Return ResourceManager.GetString("Remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Replace.
        '''</summary>
        Friend ReadOnly Property Replace() As String
            Get
                Return ResourceManager.GetString("Replace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Replace Ctrl+H.
        '''</summary>
        Friend ReadOnly Property Replace1() As String
            Get
                Return ResourceManager.GetString("Replace1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset.
        '''</summary>
        Friend ReadOnly Property Reset() As String
            Get
                Return ResourceManager.GetString("Reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reshape.
        '''</summary>
        Friend ReadOnly Property Reshape() As String
            Get
                Return ResourceManager.GetString("Reshape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resize Worksheet.
        '''</summary>
        Friend ReadOnly Property Resize_Worksheet() As String
            Get
                Return ResourceManager.GetString("Resize_Worksheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Row_Statistics.
        '''</summary>
        Friend ReadOnly Property Row_Statistics() As String
            Get
                Return ResourceManager.GetString("Row_Statistics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run Worksheet Editor F7.
        '''</summary>
        Friend ReadOnly Property Run_Worksheet_Editor() As String
            Get
                Return ResourceManager.GetString("Run_Worksheet_Editor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sample Size.
        '''</summary>
        Friend ReadOnly Property Sample_Size() As String
            Get
                Return ResourceManager.GetString("Sample_Size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save As.
        '''</summary>
        Friend ReadOnly Property Save_As() As String
            Get
                Return ResourceManager.GetString("Save_As", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ScatterPlot....
        '''</summary>
        Friend ReadOnly Property ScatterPlot() As String
            Get
                Return ResourceManager.GetString("ScatterPlot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script.
        '''</summary>
        Friend ReadOnly Property Script() As String
            Get
                Return ResourceManager.GetString("Script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script Window.
        '''</summary>
        Friend ReadOnly Property Script_Window() As String
            Get
                Return ResourceManager.GetString("Script_Window", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select.
        '''</summary>
        Friend ReadOnly Property Select_() As String
            Get
                Return ResourceManager.GetString("Select_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select All.
        '''</summary>
        Friend ReadOnly Property Select_All() As String
            Get
                Return ResourceManager.GetString("Select_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select All ctrls+A .
        '''</summary>
        Friend ReadOnly Property Select_All1() As String
            Get
                Return ResourceManager.GetString("Select_All1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select and Stack.
        '''</summary>
        Friend ReadOnly Property Select_and_Stack() As String
            Get
                Return ResourceManager.GetString("Select_and_Stack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected Variables.
        '''</summary>
        Friend ReadOnly Property Selected_Variables() As String
            Get
                Return ResourceManager.GetString("Selected_Variables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selection.
        '''</summary>
        Friend ReadOnly Property Selection() As String
            Get
                Return ResourceManager.GetString("Selection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Simple Models.
        '''</summary>
        Friend ReadOnly Property Simple_Models() As String
            Get
                Return ResourceManager.GetString("Simple_Models", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort.
        '''</summary>
        Friend ReadOnly Property Sort() As String
            Get
                Return ResourceManager.GetString("Sort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spells.
        '''</summary>
        Friend ReadOnly Property Spells() As String
            Get
                Return ResourceManager.GetString("Spells", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stack.
        '''</summary>
        Friend ReadOnly Property Stack() As String
            Get
                Return ResourceManager.GetString("Stack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start of the Rains.
        '''</summary>
        Friend ReadOnly Property Start_of_the_Rains() As String
            Get
                Return ResourceManager.GetString("Start_of_the_Rains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Statistics.
        '''</summary>
        Friend ReadOnly Property Statistics() As String
            Get
                Return ResourceManager.GetString("Statistics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stem And Leaf.
        '''</summary>
        Friend ReadOnly Property Stem_And_Leaf() As String
            Get
                Return ResourceManager.GetString("Stem_And_Leaf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit.
        '''</summary>
        Friend ReadOnly Property Submit() As String
            Get
                Return ResourceManager.GetString("Submit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary.
        '''</summary>
        Friend ReadOnly Property Summary() As String
            Get
                Return ResourceManager.GetString("Summary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary Chart.
        '''</summary>
        Friend ReadOnly Property Summary_Chart() As String
            Get
                Return ResourceManager.GetString("Summary_Chart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Survival.
        '''</summary>
        Friend ReadOnly Property Survival() As String
            Get
                Return ResourceManager.GetString("Survival", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tables.
        '''</summary>
        Friend ReadOnly Property Tables() As String
            Get
                Return ResourceManager.GetString("Tables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Threashold.
        '''</summary>
        Friend ReadOnly Property Threashold() As String
            Get
                Return ResourceManager.GetString("Threashold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time Series.
        '''</summary>
        Friend ReadOnly Property Time_Series() As String
            Get
                Return ResourceManager.GetString("Time_Series", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Rain.
        '''</summary>
        Friend ReadOnly Property Total_Rain() As String
            Get
                Return ResourceManager.GetString("Total_Rain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transform.
        '''</summary>
        Friend ReadOnly Property Transform() As String
            Get
                Return ResourceManager.GetString("Transform", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Undo.
        '''</summary>
        Friend ReadOnly Property Undo() As String
            Get
                Return ResourceManager.GetString("Undo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unstack.
        '''</summary>
        Friend ReadOnly Property Unstack() As String
            Get
                Return ResourceManager.GetString("Unstack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View/Edit Macro.
        '''</summary>
        Friend ReadOnly Property View_Edit_Macro() As String
            Get
                Return ResourceManager.GetString("View_Edit_Macro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View/Edit Text.
        '''</summary>
        Friend ReadOnly Property View_Edit_Text() As String
            Get
                Return ResourceManager.GetString("View_Edit_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Water Balance.
        '''</summary>
        Friend ReadOnly Property Water_Balance() As String
            Get
                Return ResourceManager.GetString("Water_Balance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Window.
        '''</summary>
        Friend ReadOnly Property Window() As String
            Get
                Return ResourceManager.GetString("Window", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windrose.
        '''</summary>
        Friend ReadOnly Property Windrose() As String
            Get
                Return ResourceManager.GetString("Windrose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Within.
        '''</summary>
        Friend ReadOnly Property Within() As String
            Get
                Return ResourceManager.GetString("Within", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
